import Phaser from 'phaser';
import '../safe-area.css';
import { BootScene } from './scenes/BootScene.js';
import { MenuScene } from './scenes/MenuRewardedAdsScene.js';
import { SettingsScene } from './scenes/SettingsGraphicsQualityScene.js';
import { installMenuMusic } from './audio/MenuMusic.js';
import { installRuntimeCrashDiagnostics } from './dev/runtimeCrashDiagnostics.js';
import { installSeasonRewardCelebrations } from './seasons/seasonRewardCelebrationTouchSafe.js';
import { initLanguage } from './i18n/index.js';
import { localizeLegacyText } from './i18n/legacyUiText.js';
import { installDomUiEnglishBridge } from './i18n/domUiEnglishBridge.js';
import { installSafeAreaRuntime } from './ui/safeArea.js';
import { installOrientationViewportSettle } from './ui/orientationViewportSettle.js';
import { installHtmlTextRuntime } from './ui/htmlTextRuntime.js';
import './tracks/trackPublicNames.js';
import { installRacePerformanceProbe } from './dev/racePerformanceProbe.js';
import { IS_PROD_BUILD } from './buildTarget.js';
class MenuAliasScene extends Phaser.Scene { constructor(){super('MenuScene');} create(){this.scene.start('menu');} }
const PLAYER_LAZY_SCENES={GarageScene:{load:()=>import('./scenes/GarageSelectionCenterScene.js'),exportName:'GarageScene',warm:10},'upgrade-shop':{load:()=>import('./scenes/UpgradeWorkshopCarUnlockScene.js'),exportName:'UpgradeShopScene',warm:20},StatsScene:{load:()=>import('./scenes/StatsTesterExchangeScene.js'),exportName:'StatsScene',warm:40},season:{load:()=>import('./scenes/SeasonSafeDockScene.js'),exportName:'SeasonScene',warm:50},TrackGarageScene:{load:()=>import('./scenes/TrackGarageAndroidTouchScene.js'),exportName:'TrackGarageScene',warm:60},race:{load:async()=>{const [{RaceScene},{installExactRuntimeBeautyPass},{installRaceEnvironmentRuntime},{installRaceGraphicsBudgetRuntime},{installRaceLoadingExperience},{installLiveDeltaReferenceRuntime}]=await Promise.all([import('./scenes/RaceEmbeddedReplaySceneV2.js'),import('./scenes/raceExactRuntimeBeautyPass.js'),import('./scenes/raceEnvironmentRuntime.js'),import('./scenes/raceGraphicsBudgetRuntime.js'),import('./ui/raceLoadingExperience.js'),import('./ui/liveDeltaReferenceRuntime.js')]);installRaceEnvironmentRuntime(RaceScene);installRaceGraphicsBudgetRuntime(RaceScene);installExactRuntimeBeautyPass(RaceScene);installRaceLoadingExperience(RaceScene);installLiveDeltaReferenceRuntime(RaceScene);
// DEV 1.1.28 regression A/B: Android races run without the diagnostic profiler.
// The probe was added after the known-good Beta 1 baseline and has its own
// requestAnimationFrame loop + postrender/update instrumentation. Keep iOS/web
// unchanged so this is a single-variable Android test.
if(!IS_PROD_BUILD&&!/Android/i.test(String(navigator?.userAgent||'')))installRacePerformanceProbe(RaceScene);
return {RaceScene};},exportName:'RaceScene',warm:70},GarageDetailScene:{load:()=>import('./scenes/GarageDetailSpeedConsistencyScene.js'),exportName:'GarageDetailScene',warm:80}};
const DEV_LAZY_SCENES=IS_PROD_BUILD?{}:{'admin-hub':{load:()=>import('./scenes/AdminHubScene.js'),exportName:'AdminHubScene',admin:true},CarEditorScene:{load:()=>import('./scenes/CarEditorSpeedConsistencyScene.js'),exportName:'CarEditorScene',admin:true},TrackEditorScene:{load:()=>import('./scenes/TrackEditorScene.js'),exportName:'TrackEditorScene',admin:true},TrackStudioScene:{load:()=>import('./scenes/TrackStudioScene.js'),exportName:'TrackStudioScene',admin:true},EnvironmentBuilderScene:{load:()=>import('./scenes/EnvironmentBuilderMaterialStudioScene.js'),exportName:'EnvironmentBuilderScene',admin:true}};
const LAZY_SCENES={...PLAYER_LAZY_SCENES,...DEV_LAZY_SCENES};
const lazyPromises=new Map();let lazyGame=null;function sceneExists(game,key){try{return !!game?.scene?.keys?.[key];}catch{return false;}}async function ensureLazyScene(key){const game=lazyGame,def=LAZY_SCENES[key];if(!game||!def)return false;if(sceneExists(game,key))return true;if(lazyPromises.has(key))return lazyPromises.get(key);const p=(async()=>{try{const mod=await def.load(),SceneClass=mod?.[def.exportName];if(typeof SceneClass!=='function')throw new Error(`Missing scene export ${def.exportName}`);if(!sceneExists(game,key))game.scene.add(key,SceneClass,false);return true;}catch(err){console.error(`[lazy-scene] ${key} failed`,err);return false;}finally{lazyPromises.delete(key);}})();lazyPromises.set(key,p);return p;}function installLazySceneNavigation(game){lazyGame=game;const proto=Phaser.Scenes.ScenePlugin?.prototype;if(!proto||proto.__tdrLazyStartInstalled)return;const originalStart=proto.start;proto.start=function(key,data){const target=String(key||'');if(LAZY_SCENES[target]&&!sceneExists(game,target)){ensureLazyScene(target).then(ok=>{if(ok){try{originalStart.call(this,target,data);}catch(err){console.error(`[lazy-scene] start ${target} failed`,err);}}});return this;}return originalStart.call(this,key,data);};proto.__tdrLazyStartInstalled=true;}
function isIOSDevice(){try{const ua=String(navigator?.userAgent||''),platform=String(navigator?.platform||'');return /iPhone|iPad|iPod/i.test(ua)||(platform==='MacIntel'&&Number(navigator?.maxTouchPoints||0)>1);}catch{return false;}}function isMobileDevice(){try{return /Android|iPhone|iPad|iPod/i.test(String(navigator?.userAgent||''))||(Number(navigator?.maxTouchPoints||0)>1&&Math.min(Number(screen?.width||0),Number(screen?.height||0))<1100);}catch{return false;}}function scheduleSceneWarmup(){if(isMobileDevice())return;const warm=Object.entries(LAZY_SCENES).filter(([,def])=>Number.isFinite(def.warm)&&!def.admin&&def.exportName!=='RaceScene').sort((a,b)=>a[1].warm-b[1].warm);let cancelled=false;const cancel=()=>{cancelled=true;window.removeEventListener('pointerdown',cancel,true);window.removeEventListener('keydown',cancel,true);};const run=async()=>{await new Promise(resolve=>{if(typeof window.requestIdleCallback==='function')window.requestIdleCallback(()=>resolve(),{timeout:2500});else setTimeout(resolve,1800);});for(const [key] of warm){if(cancelled||document.hidden)break;await ensureLazyScene(key);await new Promise(resolve=>{if(typeof window.requestIdleCallback==='function')window.requestIdleCallback(()=>resolve(),{timeout:700});else setTimeout(resolve,180);});}cancel();};window.addEventListener('pointerdown',cancel,true);window.addEventListener('keydown',cancel,true);window.addEventListener('tdr:bootready',()=>{run().catch(()=>cancel());},{once:true});}
function videoPrefs(){try{const s=JSON.parse(localStorage.getItem('tdr2:settings')||'{}'),v=s?.video||{},quality=String(v.quality||'high'),preset=String(v.preset||(quality==='low'?'performance':quality==='medium'?'medium':'high')).toLowerCase(),dpr=Math.max(1,Number(window.devicePixelRatio)||1),android=/Android/i.test(String(navigator?.userAgent||'')),renderResolution=android?1:(preset==='performance'?1:preset==='medium'?Math.min(dpr,1.25):preset==='ultra'?Math.min(dpr,2):Math.min(dpr,1.5));return{quality,preset,targetFps:60,antialias:typeof v.antialias==='boolean'?v.antialias:quality!=='low',renderResolution};}catch{return{quality:'high',preset:'high',targetFps:60,antialias:true,renderResolution:1.5};}}function isLegacyIOSPhone(){try{if(!isIOSDevice())return false;const manualSafe=localStorage.getItem('tdr2:forceIosSafeMode')==='1';const autoSafeUntil=Number(localStorage.getItem('tdr2:autoIosSafeModeUntil')||0);const autoSafe=Number.isFinite(autoSafeUntil)&&autoSafeUntil>Date.now();return manualSafe||autoSafe;}catch{return false;}}function forceRafLoop(){try{return localStorage.getItem('tdr2:forceRafLoop')==='1';}catch{return false;}}function localizePhaserValue(value){return localizeLegacyText(value);}function installCleanTextFactory(){const factory=Phaser.GameObjects?.GameObjectFactory?.prototype;if(factory&&!factory.__tdrCleanTextInstalled&&typeof factory.text==='function'){const original=factory.text;factory.text=function(x,y,text,style={}){const clean={...(style||{})};if(/Orbitron/i.test(String(clean.fontFamily||''))){clean.fontFamily='system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';if(clean.fontStyle==='900')clean.fontStyle='bold';}if(Number(clean.strokeThickness)>2)clean.strokeThickness=2;return original.call(this,x,y,localizePhaserValue(text),clean);};factory.__tdrCleanTextInstalled=true;}const textProto=Phaser.GameObjects?.Text?.prototype;if(textProto&&!textProto.__tdrLegacyLocalizationInstalled&&typeof textProto.setText==='function'){const originalSetText=textProto.setText;textProto.setText=function(value){return originalSetText.call(this,localizePhaserValue(value));};textProto.__tdrLegacyLocalizationInstalled=true;}}function installSafeTextureGuard(){const classes=[Phaser.GameObjects?.Image,Phaser.GameObjects?.Sprite,Phaser.GameObjects?.TileSprite].filter(Boolean);for(const Klass of classes){const proto=Klass?.prototype;if(!proto||proto.__tdrSafeTextureGuard||typeof proto.setTexture!=='function')continue;const original=proto.setTexture;proto.setTexture=function(...args){if(!this?.scene?.sys?.textures)return this;return original.apply(this,args);};proto.__tdrSafeTextureGuard=true;}}
export function createGame(parentId='app'){installSafeAreaRuntime();initLanguage();installDomUiEnglishBridge();installSeasonRewardCelebrations();installCleanTextFactory();installSafeTextureGuard();const vp=videoPrefs(),iosDevice=isIOSDevice(),safeMode=isLegacyIOSPhone();try{window.__tdrIosSafeMode=safeMode;window.__tdrVideoPreset=vp.preset;window.__tdrRenderResolution=vp.renderResolution;}catch{}const antialias=iosDevice?false:!!vp.antialias,targetFps=safeMode?30:60;const batchSize=iosDevice?1024:4096;const forceSetTimeOut=safeMode&&!forceRafLoop();const game=new Phaser.Game({type:Phaser.AUTO,parent:parentId,backgroundColor:'#0b1020',resolution:vp.renderResolution,fps:{target:targetFps,min:safeMode?15:20,forceSetTimeOut},scene:[BootScene,MenuScene,MenuAliasScene,SettingsScene],dom:{createContainer:true},scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH},physics:{default:'arcade',arcade:{debug:false}},render:{pixelArt:false,antialias,antialiasGL:antialias,desynchronized:iosDevice,roundPixels:safeMode,powerPreference:'high-performance',batchSize}});installHtmlTextRuntime(game);installLazySceneNavigation(game);scheduleSceneWarmup();if(!IS_PROD_BUILD){try{window.__tdrEnsureScene=ensureLazyScene;}catch{}}try{const canvas=game.canvas;if(canvas?.style){canvas.style.imageRendering='auto';canvas.style.webkitFontSmoothing='antialiased';canvas.style.textRendering='optimizeLegibility';}}catch{}installOrientationViewportSettle(game);if(!IS_PROD_BUILD)installRuntimeCrashDiagnostics(game);installMenuMusic(game);return game;}
