const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const xy=(p)=>Array.isArray(p)?{x:+p[0],y:+p[1]}:{x:+p?.x,y:+p?.y};
const point=(p,w)=>Array.isArray(p)?{x:+p[0],y:+p[1],width:+(p[2]||w)}:{x:+p?.x,y:+p?.y,width:+(p?.width||w)};
function slug(v){return String(v||'circuito').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')||'circuito';}

export function computeTrackExportBounds(scene){
  const w=+(scene.track?.meta?.trackWidth||160),pts=[];
  const add=a=>{if(Array.isArray(a))for(const p of a){const q=xy(p);if(Number.isFinite(q.x)&&Number.isFinite(q.y))pts.push(q);}};
  add(scene.track?.geom?.grass?.left);add(scene.track?.geom?.grass?.right);add(scene.track?.geom?.left);add(scene.track?.geom?.right);
  for(const o of(scene._circuitEnvironment||[])){if(!o?.scene||!Number.isFinite(o.x)||!Number.isFinite(o.y))continue;const hw=Math.abs(+(o.displayWidth||0))*.65,hh=Math.abs(+(o.displayHeight||0))*.65;pts.push({x:o.x-hw,y:o.y-hh},{x:o.x+hw,y:o.y+hh});}
  if(!pts.length){const b=scene.physics?.world?.bounds;if(!b?.width||!b?.height)return null;return{x:+b.x||0,y:+b.y||0,width:+b.width,height:+b.height,padWorld:0};}
  let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of pts){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y);}const pad=Math.max(90,w*.45);
  return{x:minX-pad,y:minY-pad,width:maxX-minX+pad*2,height:maxY-minY+pad*2,padWorld:pad};
}

function geometry(bounds,opt={}){const long=clamp(Math.round(+(opt.longSide||3200)),1536,3200),pad=Math.max(32,Math.round(+(opt.paddingPx||96))),s=(long-pad*2)/Math.max(bounds.width,bounds.height);let width=Math.ceil(bounds.width*s+pad*2),height=Math.ceil(bounds.height*s+pad*2);if(width%2)width++;if(height%2)height++;return{width,height,paddingPx:pad,scale:s};}
function gate(g){if(!g?.a||!g?.b)return null;return{a:{x:+g.a.x,y:+g.a.y},b:{x:+g.b.x,y:+g.b.y}};}
export function buildTrackMapping(scene,kind,b,g){const ox=b.x-g.paddingPx/g.scale,oy=b.y-g.paddingPx/g.scale,w=+(scene.track?.meta?.trackWidth||160),raw=scene.track?.geom?.center||scene.track?.meta?.centerline||[];return{version:9,type:'topdown-race-world-map',trackId:scene.trackKey||scene.track?.meta?.id||'track',trackName:scene.track?.meta?.name||scene.trackKey||'track',variant:kind==='technical'?'technical':'world',generatedAt:new Date().toISOString(),image:{width:g.width,height:g.height,paddingPx:g.paddingPx},worldBounds:{x:b.x,y:b.y,width:b.width,height:b.height,minX:b.x,minY:b.y,maxX:b.x+b.width,maxY:b.y+b.height,safetyOverscanWorld:b.padWorld},transform:{pixelsPerWorldUnit:g.scale,worldUnitsPerPixel:1/g.scale,worldOriginAtImagePixel00:{x:ox,y:oy},formulas:{worldToPixel:'px=(worldX-worldOriginX)*pixelsPerWorldUnit; py=(worldY-worldOriginY)*pixelsPerWorldUnit',pixelToWorld:'worldX=worldOriginX+px*worldUnitsPerPixel; worldY=worldOriginY+py*worldUnitsPerPixel'}},renderer:{mode:'phaser-offscreen-rendertexture-safe',source:'live-race-display-list',reconstructedGeometry:false,maxLongSide:3200,originMode:'camera-centerOn',infoCard:true},track:{nominalWidth:+(scene.track?.meta?.trackWidth||0)||null,centerline:raw.map(p=>point(p,w)).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)),finish:gate(scene.finishLine||scene.track?.meta?.finishLine||scene.track?.meta?.finish),checkpoint1:gate(scene.checkpoints?.cp1),checkpoint2:gate(scene.checkpoints?.cp2)}};}

function snapshotRT(rt){return new Promise((res,rej)=>{try{rt.snapshot(img=>img?res(img):rej(new Error('Snapshot vacío')),'image/png',1);}catch(e){rej(e);}});}
function trackLength(center){if(!Array.isArray(center)||center.length<2)return 0;let d=0;for(let i=1;i<center.length;i++)d+=Math.hypot(center[i].x-center[i-1].x,center[i].y-center[i-1].y);if(center.length>2)d+=Math.hypot(center[0].x-center.at(-1).x,center[0].y-center.at(-1).y);return d;}
function worldPx(map,x,y){const t=map.transform;return{x:(x-t.worldOriginAtImagePixel00.x)*t.pixelsPerWorldUnit,y:(y-t.worldOriginAtImagePixel00.y)*t.pixelsPerWorldUnit};}
function chooseCardCorner(scene,map,w,h,cw,ch,m){const corners=[{x:m,y:m},{x:w-cw-m,y:m},{x:m,y:h-ch-m},{x:w-cw-m,y:h-ch-m}],pts=[];for(const p of(map.track?.centerline||[])){const q=worldPx(map,p.x,p.y);pts.push(q);}for(const o of(scene._circuitEnvironment||[])){if(Number.isFinite(o?.x)&&Number.isFinite(o?.y))pts.push(worldPx(map,o.x,o.y));}const gates=[map.track?.finish,map.track?.checkpoint1,map.track?.checkpoint2];for(const g of gates)if(g?.a&&g?.b){pts.push(worldPx(map,g.a.x,g.a.y),worldPx(map,g.b.x,g.b.y));}let best=corners[0],score=Infinity;for(const c of corners){let s=0;const x0=c.x-m*.5,y0=c.y-m*.5,x1=c.x+cw+m*.5,y1=c.y+ch+m*.5;for(const p of pts)if(p.x>=x0&&p.x<=x1&&p.y>=y0&&p.y<=y1)s++;if(s<score){score=s;best=c;}}return best;}
function drawInfoCard(ctx,scene,map,w,h){const scale=Math.max(.75,Math.min(1.35,h/3200));const cw=Math.round(clamp(w*.29,470,720)*scale),ch=Math.round(300*scale),m=Math.round(58*scale),p=Math.round(30*scale);const pos=chooseCardCorner(scene,map,w,h,cw,ch,m);const meta=scene.track?.meta||{},center=map.track?.centerline||[],len=trackLength(center),sectors=1+(map.track?.checkpoint1?1:0)+(map.track?.checkpoint2?1:0),surface=meta.surface||meta.surfaceName||meta.roadSurface||'Asfalto',name=String(map.trackName||'Circuito').toUpperCase(),width=map.track?.nominalWidth;const rows=[['CIRCUITO',name],['LONGITUD',len?`${Math.round(len)} u`:'—'],['SECTORES',String(sectors)],['SUPERFICIE',String(surface)],['ANCHO PISTA',width?`${Math.round(width)} u`:'—']];ctx.save();ctx.fillStyle='rgba(7,12,15,.78)';ctx.strokeStyle='rgba(215,235,240,.68)';ctx.lineWidth=Math.max(2,Math.round(2*scale));const r=Math.round(18*scale);ctx.beginPath();ctx.roundRect(pos.x,pos.y,cw,ch,r);ctx.fill();ctx.stroke();ctx.fillStyle='#f5f7f8';ctx.font=`700 ${Math.round(30*scale)}px system-ui,-apple-system,sans-serif`;ctx.fillText('FICHA DEL CIRCUITO',pos.x+p,pos.y+Math.round(48*scale));ctx.strokeStyle='rgba(255,255,255,.32)';ctx.beginPath();ctx.moveTo(pos.x+p,pos.y+Math.round(66*scale));ctx.lineTo(pos.x+cw-p,pos.y+Math.round(66*scale));ctx.stroke();let y=pos.y+Math.round(105*scale);const labelX=pos.x+p,valueX=pos.x+Math.round(cw*.48);for(const [a,b] of rows){ctx.fillStyle='rgba(230,235,238,.78)';ctx.font=`600 ${Math.round(24*scale)}px system-ui,-apple-system,sans-serif`;ctx.fillText(a,labelX,y);ctx.fillStyle='#fff';ctx.font=`500 ${Math.round(25*scale)}px system-ui,-apple-system,sans-serif`;ctx.fillText(b,valueX,y);y+=Math.round(39*scale);}ctx.restore();map.infoCard={visible:true,corner:(pos.x<w/2?'left':'right')+'-'+(pos.y<h/2?'top':'bottom'),fields:{name,lengthWorldUnits:len||null,sectors,surface,trackWidthWorldUnits:width||null}};}
function imageBlob(scene,img,map){return new Promise((res,rej)=>{const c=document.createElement('canvas');c.width=img.naturalWidth||img.width;c.height=img.naturalHeight||img.height;const x=c.getContext('2d');if(!x)return rej(new Error('Canvas no disponible'));x.drawImage(img,0,0);drawInfoCard(x,scene,map,c.width,c.height);c.toBlob(b=>b?res(b):rej(new Error('PNG falló')),'image/png');});}
async function deliver(scene,img,map,kind){const base=slug(scene.track?.meta?.name||scene.trackKey),png=`${base}-${kind==='technical'?'technical-hd':'world-hd'}.png`,json=`${base}-mapping.json`,pb=await imageBlob(scene,img,map),jb=new Blob([JSON.stringify(map,null,2)],{type:'application/json'});try{if(navigator?.share&&typeof File!=='undefined'){const files=[new File([pb],png,{type:'image/png'}),new File([jb],json,{type:'application/json'})];if(!navigator.canShare||navigator.canShare({files})){await navigator.share({files,title:`Mapa ${map.trackName}`});return;}}}catch(_){}const dl=(b,n)=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);};dl(pb,png);setTimeout(()=>dl(jb,json),220);}

function forceTrackCellsVisible(scene){const saved=[];const setObj=o=>{if(!o||typeof o!=='object')return;for(const k of['tile','gfx','graphics','asphalt','grass','curb']){const x=o[k];if(x?.scene&&typeof x.visible==='boolean'){saved.push([x,x.visible]);x.setVisible?.(true);}}if(o.scene&&typeof o.visible==='boolean'){saved.push([o,o.visible]);o.setVisible?.(true);}};try{for(const cell of(scene.track?.gfxByCell?.values?.()||[]))setObj(cell);}catch(_){}return()=>{for(const [o,v] of saved)try{o.setVisible?.(v);}catch(_){}};}

async function renderOffscreen(scene,g,map){let rt=null;const restoreCells=forceTrackCellsVisible(scene);const fixed=[];try{for(const o of(scene.children?.list||[])){if(!o?.scene)continue;if((o.scrollFactorX??1)===0&&(o.scrollFactorY??1)===0&&o.visible!==false){fixed.push(o);o.setVisible?.(false);}}rt=scene.add.renderTexture(0,0,g.width,g.height).setOrigin(0,0).setVisible(false);rt.camera.setZoom(g.scale);const wb=map.worldBounds;rt.camera.centerOn(wb.x+wb.width*.5,wb.y+wb.height*.5);rt.camera.roundPixels=false;scene.children?.depthSort?.();rt.draw(scene.children);return await snapshotRT(rt);}finally{try{rt?.destroy?.();}catch(_){}for(const o of fixed)try{o.setVisible?.(true);}catch(_){}restoreCells();}}

export async function exportTrackMapHD(scene,kind='world',opt={}){const b=computeTrackExportBounds(scene);if(!b)throw new Error('Bounds no disponibles');const g=geometry(b,{...opt,longSide:Math.min(+(opt.longSide||3200),3200)}),map=buildTrackMapping(scene,kind,b,g),img=await renderOffscreen(scene,g,map);await deliver(scene,img,map,kind);return{mapping:map,width:g.width,height:g.height};}
