const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const xy=(p)=>Array.isArray(p)?{x:+p[0],y:+p[1]}:{x:+p?.x,y:+p?.y};
const point=(p,w)=>Array.isArray(p)?{x:+p[0],y:+p[1],width:+(p[2]||w)}:{x:+p?.x,y:+p?.y,width:+(p?.width||w)};
function slug(v){return String(v||'circuito').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')||'circuito';}

export function computeTrackExportBounds(scene){
  const w=+(scene.track?.meta?.trackWidth||160),pts=[];
  const add=a=>{if(Array.isArray(a))for(const p of a){const q=xy(p);if(Number.isFinite(q.x)&&Number.isFinite(q.y))pts.push(q);}};
  add(scene.track?.geom?.grass?.left);add(scene.track?.geom?.grass?.right);add(scene.track?.geom?.left);add(scene.track?.geom?.right);
  for(const o of(scene._circuitEnvironment||[])){if(!o?.scene||!Number.isFinite(o.x)||!Number.isFinite(o.y))continue;const hw=Math.abs(+(o.displayWidth||0))*.65,hh=Math.abs(+(o.displayHeight||0))*.65;pts.push({x:o.x-hw,y:o.y-hh},{x:o.x+hw,y:o.y+hh});}
  if(!pts.length){const b=scene.physics?.world?.bounds;if(!b?.width||!b?.height)return null;return{x:+b.x||0,y:+b.y||0,width:+b.width,height:+b.height,padWorld:0};}
  let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of pts){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y);}const pad=Math.max(90,w*.45);
  return{x:minX-pad,y:minY-pad,width:maxX-minX+pad*2,height:maxY-minY+pad*2,padWorld:pad};
}

function geometry(bounds,opt={}){const long=clamp(Math.round(+(opt.longSide||3200)),1536,3200),pad=Math.max(32,Math.round(+(opt.paddingPx||96))),s=(long-pad*2)/Math.max(bounds.width,bounds.height);let width=Math.ceil(bounds.width*s+pad*2),height=Math.ceil(bounds.height*s+pad*2);if(width%2)width++;if(height%2)height++;return{width,height,paddingPx:pad,scale:s};}
function gate(g){if(!g?.a||!g?.b)return null;return{a:{x:+g.a.x,y:+g.a.y},b:{x:+g.b.x,y:+g.b.y}};}
export function buildTrackMapping(scene,kind,b,g){const ox=b.x-g.paddingPx/g.scale,oy=b.y-g.paddingPx/g.scale,w=+(scene.track?.meta?.trackWidth||160),raw=scene.track?.geom?.center||scene.track?.meta?.centerline||[];return{version:7,type:'topdown-race-world-map',trackId:scene.trackKey||scene.track?.meta?.id||'track',trackName:scene.track?.meta?.name||scene.trackKey||'track',variant:kind==='technical'?'technical':'world',generatedAt:new Date().toISOString(),image:{width:g.width,height:g.height,paddingPx:g.paddingPx},worldBounds:{x:b.x,y:b.y,width:b.width,height:b.height,minX:b.x,minY:b.y,maxX:b.x+b.width,maxY:b.y+b.height,safetyOverscanWorld:b.padWorld},transform:{pixelsPerWorldUnit:g.scale,worldUnitsPerPixel:1/g.scale,worldOriginAtImagePixel00:{x:ox,y:oy},formulas:{worldToPixel:'px=(worldX-worldOriginX)*pixelsPerWorldUnit; py=(worldY-worldOriginY)*pixelsPerWorldUnit',pixelToWorld:'worldX=worldOriginX+px*worldUnitsPerPixel; worldY=worldOriginY+py*worldUnitsPerPixel'}},renderer:{mode:'phaser-offscreen-rendertexture-safe',source:'live-race-display-list',reconstructedGeometry:false,maxLongSide:3200,originMode:'display-list-offset'},track:{nominalWidth:+(scene.track?.meta?.trackWidth||0)||null,centerline:raw.map(p=>point(p,w)).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)),finish:gate(scene.finishLine||scene.track?.meta?.finishLine||scene.track?.meta?.finish),checkpoint1:gate(scene.checkpoints?.cp1),checkpoint2:gate(scene.checkpoints?.cp2)}};}

function snapshotRT(rt){return new Promise((res,rej)=>{try{rt.snapshot(img=>img?res(img):rej(new Error('Snapshot vacío')),'image/png',1);}catch(e){rej(e);}});}
function imageBlob(img){return new Promise((res,rej)=>{const c=document.createElement('canvas');c.width=img.naturalWidth||img.width;c.height=img.naturalHeight||img.height;const x=c.getContext('2d');if(!x)return rej(new Error('Canvas no disponible'));x.drawImage(img,0,0);c.toBlob(b=>b?res(b):rej(new Error('PNG falló')),'image/png');});}
async function deliver(scene,img,map,kind){const base=slug(scene.track?.meta?.name||scene.trackKey),png=`${base}-${kind==='technical'?'technical-hd':'world-hd'}.png`,json=`${base}-mapping.json`,pb=await imageBlob(img),jb=new Blob([JSON.stringify(map,null,2)],{type:'application/json'});try{if(navigator?.share&&typeof File!=='undefined'){const files=[new File([pb],png,{type:'image/png'}),new File([jb],json,{type:'application/json'})];if(!navigator.canShare||navigator.canShare({files})){await navigator.share({files,title:`Mapa ${map.trackName}`});return;}}}catch(_){}const dl=(b,n)=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);};dl(pb,png);setTimeout(()=>dl(jb,json),220);}

function forceTrackCellsVisible(scene){const saved=[];const setObj=o=>{if(!o||typeof o!=='object')return;for(const k of['tile','gfx','graphics','asphalt','grass','curb']){const x=o[k];if(x?.scene&&typeof x.visible==='boolean'){saved.push([x,x.visible]);x.setVisible?.(true);}}if(o.scene&&typeof o.visible==='boolean'){saved.push([o,o.visible]);o.setVisible?.(true);}};try{for(const cell of(scene.track?.gfxByCell?.values?.()||[]))setObj(cell);}catch(_){}return()=>{for(const [o,v] of saved)try{o.setVisible?.(v);}catch(_){}};}

async function renderOffscreen(scene,g,map){let rt=null;const restoreCells=forceTrackCellsVisible(scene);const fixed=[];try{for(const o of(scene.children?.list||[])){if(!o?.scene)continue;if((o.scrollFactorX??1)===0&&(o.scrollFactorY??1)===0&&o.visible!==false){fixed.push(o);o.setVisible?.(false);}}rt=scene.add.renderTexture(0,0,g.width,g.height).setOrigin(0,0).setVisible(false);rt.camera.setZoom(g.scale);rt.camera.setScroll(0,0);rt.camera.roundPixels=false;scene.children?.depthSort?.();const origin=map.transform.worldOriginAtImagePixel00;rt.draw(scene.children,-origin.x,-origin.y);return await snapshotRT(rt);}finally{try{rt?.destroy?.();}catch(_){}for(const o of fixed)try{o.setVisible?.(true);}catch(_){}restoreCells();}}

export async function exportTrackMapHD(scene,kind='world',opt={}){const b=computeTrackExportBounds(scene);if(!b)throw new Error('Bounds no disponibles');const g=geometry(b,{...opt,longSide:Math.min(+(opt.longSide||3200),3200)}),map=buildTrackMapping(scene,kind,b,g),img=await renderOffscreen(scene,g,map);await deliver(scene,img,map,kind);return{mapping:map,width:g.width,height:g.height};}
