import { CAR_SPECS } from '../cars/carSpecs.js';
import { getLanguage } from '../i18n/index.js';
import { getTrackPublicName } from '../tracks/trackPublicNames.js';
import { TRACK_REGISTRY } from '../tracks/trackRegistry.js';

const BASE=import.meta.env.BASE_URL||'/';
const ROOT_ID='tdr-race-loading-experience';
const STYLE_ID='tdr-race-loading-experience-style-v3';
const RECENT_KEY='tdr2:raceLoadingTipsRecent';
const RECENT_LIMIT=7;
const TIP_ROTATE_MS=11000;
const READY_MIN_MS=260;
const READY_TIMEOUT_MS=10000;

const TIPS=[
['drive-01','CONDUCCIÓN','DRIVING','Frena antes de girar.','Brake before you turn.'],
['drive-02','CONDUCCIÓN','DRIVING','En recta, mueve el volante lo mínimo.','On straights, steer as little as possible.'],
['drive-03','CONDUCCIÓN','DRIVING','Acelera cuando el coche apunte a la salida.','Accelerate when the car points toward the exit.'],
['drive-04','CONDUCCIÓN','DRIVING','Una salida limpia de curva gana tiempo.','A clean corner exit saves time.'],
['drive-05','CONDUCCIÓN','DRIVING','No entres pasado: perderás la salida.','Do not overcook entry: you will lose the exit.'],
['drive-06','CONDUCCIÓN','DRIVING','Frena recto antes de pedir giro al coche.','Brake straight before asking the car to turn.'],
['drive-07','CONDUCCIÓN','DRIVING','Suavidad al volante también significa velocidad.','Smooth steering also means speed.'],
['drive-08','CONDUCCIÓN','DRIVING','Mira la salida de la curva, no el morro.','Look at the corner exit, not the nose.'],
['drive-09','CONDUCCIÓN','DRIVING','Corrige menos y conservarás más velocidad.','Correct less and you will keep more speed.'],
['drive-10','CONDUCCIÓN','DRIVING','Levantar un instante puede evitar una frenada fuerte.','A short lift can avoid heavy braking.'],
['line-01','TRAZADA','RACING LINE','Busca el vértice para acortar la curva.','Aim for the apex to shorten the corner.'],
['line-02','TRAZADA','RACING LINE','Abre la entrada para mejorar la salida.','Open the entry to improve the exit.'],
['line-03','TRAZADA','RACING LINE','Las curvas lentas se ganan en la salida.','Slow corners are won on exit.'],
['line-04','TRAZADA','RACING LINE','No todas las curvas piden la misma línea.','Not every corner needs the same line.'],
['line-05','TRAZADA','RACING LINE','Encadena curvas pensando en la última salida.','Link corners by planning the final exit.'],
['line-06','TRAZADA','RACING LINE','Sacrifica una curva para preparar mejor la siguiente.','Sacrifice one corner to prepare the next.'],
['line-07','TRAZADA','RACING LINE','Aprende una referencia fija para cada frenada.','Learn one fixed marker for each braking point.'],
['line-08','TRAZADA','RACING LINE','Ataca el piano solo si mejora tu trazada.','Use the kerb only if it improves your line.'],
['line-09','TRAZADA','RACING LINE','Una línea estable ayuda a alcanzar la punta.','A stable line helps you reach top speed.'],
['line-10','TRAZADA','RACING LINE','Prioriza la recta más larga al enlazar curvas.','Prioritize the longest straight when linking corners.'],
['time-01','CONTRARRELOJ','TIME ATTACK','Cada pequeña corrección cuesta tiempo.','Every small correction costs time.','timeattack'],
['time-02','CONTRARRELOJ','TIME ATTACK','Repite vueltas limpias antes de buscar el límite.','Repeat clean laps before chasing the limit.','timeattack'],
['time-03','CONTRARRELOJ','TIME ATTACK','Mejora una curva cada vez.','Improve one corner at a time.','timeattack'],
['ghost-01','FANTASMA','GHOST','El fantasma muestra dónde pierdes tiempo.','The ghost shows where you lose time.','ghost'],
['ghost-02','FANTASMA','GHOST','Compara al fantasma, no lo persigas.','Compare the ghost; do not chase it.','ghost'],
['surv-01','SUPERVIVENCIA','SURVIVAL','La constancia vale más que arriesgar cada curva.','Consistency beats risking every corner.','survival'],
['surv-02','SUPERVIVENCIA','SURVIVAL','Evita contactos y conserva tu velocidad.','Avoid contact and preserve your speed.','survival'],
['duel-01','DUELO','DUEL','Presiona al rival sin regalar tu trazada.','Pressure the rival without giving away your line.','duel'],
['duel-02','DUELO','DUEL','Una buena salida facilita el adelantamiento.','A good exit makes overtaking easier.','duel'],
['test-01','PRUEBAS','TESTING','Usa el Área de Pruebas para comparar ajustes.','Use the Test Area to compare setups.','practice'],
['test-02','PRUEBAS','TESTING','Cambia una sola cosa y compara.','Change one thing and compare.','practice'],
['car-01','COCHE','CAR','Más punta no siempre da una vuelta más rápida.','More top speed does not always mean a faster lap.'],
['car-02','COCHE','CAR','Más agarre permite acelerar antes.','More grip lets you accelerate earlier.'],
['car-03','COCHE','CAR','Conoce tu coche antes de llevarlo al límite.','Know your car before pushing its limit.'],
['car-04','COCHE','CAR','La estabilidad también es rendimiento.','Stability is also performance.'],
['car-05','COCHE','CAR','Un coche rápido necesita una trazada limpia.','A fast car still needs a clean line.'],
['factory-01','FÁBRICA','FACTORY','La Fábrica mejora el coche pieza a pieza.','The Factory improves the car part by part.'],
['factory-02','FÁBRICA','FACTORY','Cada familia de piezas cambia el coche.','Each part family changes the car.'],
['factory-03','FÁBRICA','FACTORY','Los tiers altos ofrecen mejores prestaciones.','Higher tiers offer better performance.'],
['factory-04','FÁBRICA','FACTORY','Prueba tus mejoras antes de competir.','Test your upgrades before racing.'],
['prog-01','PROGRESIÓN','PROGRESSION','Los materiales sirven para mejorar piezas.','Materials are used to improve parts.'],
['prog-02','PROGRESIÓN','PROGRESSION','Guarda recursos para la mejora que necesitas.','Save resources for the upgrade you need.'],
['prog-03','PROGRESIÓN','PROGRESSION','Completa objetivos para ampliar tus opciones.','Complete objectives to expand your options.'],
['track-01','CIRCUITO','TRACK','Aprende el circuito antes de buscar el límite.','Learn the track before chasing the limit.'],
['track-02','CIRCUITO','TRACK','Identifica curvas antes de rectas largas.','Identify corners before long straights.'],
['track-03','CIRCUITO','TRACK','Una referencia visual hace repetible tu frenada.','A visual marker makes braking repeatable.'],
['track-04','CIRCUITO','TRACK','Varias vueltas revelan la trazada ideal.','Several laps reveal the ideal line.'],
['track-05','CIRCUITO','TRACK','Salirte cuesta velocidad y tiempo.','Leaving the track costs speed and time.']
].map(([id,catEs,catEn,es,en,mode=null])=>({id,catEs,catEn,es,en,mode}));

const MODES={timeattack:{es:'CONTRARRELOJ',en:'TIME ATTACK'},ghost:{es:'FANTASMA',en:'GHOST'},survival:{es:'SUPERVIVENCIA',en:'SURVIVAL'},duel:{es:'DUELO',en:'DUEL'},practice:{es:'ÁREA DE PRUEBAS',en:'TEST AREA'}};
function lang(){return getLanguage()==='en'?'en':'es';}
function ls(key,fallback=''){try{return localStorage.getItem(key)||fallback;}catch{return fallback;}}
function quality(){try{return String(JSON.parse(localStorage.getItem('tdr2:settings')||'{}')?.video?.quality||'high').toUpperCase();}catch{return'HIGH';}}
function mode(){return ls('tdr2:gameMode','timeattack');}
function trackKey(scene){return String(scene?.trackKey||ls('tdr2:trackKey','track01')||'track01');}
function carId(scene){return String(scene?.carId||ls('tdr2:carId','avenir_gripline')||'avenir_gripline');}
function modeName(value,l){return MODES[value]?.[l]||String(value||'').toUpperCase();}
function trackName(scene,key,l){try{return getTrackPublicName(scene?.track||TRACK_REGISTRY?.[key]||key,l)||String(key).replace(/[-_]+/g,' ').toUpperCase();}catch{return String(key).replace(/[-_]+/g,' ').toUpperCase();}}
function carName(scene,id){return String(CAR_SPECS?.[id]?.name||scene?.carName||id).replace(/_/g,' ').toUpperCase();}
function trackDef(scene,key){return scene?.track||TRACK_REGISTRY?.[key]||null;}
function surfaceName(scene,key,l){const t=trackDef(scene,key),raw=String(t?.surface||t?.meta?.surface||t?.meta?.trackSurface||'asphalt');const dirt=/dirt|tierra|gravel|grava|offroad/i.test(raw);return dirt?(l==='en'?'DIRT':'TIERRA'):(l==='en'?'ASPHALT':'ASFALTO');}
function points(scene,key){const t=trackDef(scene,key);const raw=t?.raceCenterline||t?.centerline||t?.meta?.centerline||[];return(Array.isArray(raw)?raw:[]).map(p=>Array.isArray(p)?{x:Number(p[0]),y:Number(p[1])}:{x:Number(p?.x),y:Number(p?.y)}).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));}
function svg(list){if(list.length<2)return'<div class="tdr-rload-map-empty">TDR</div>';const xs=list.map(p=>p.x),ys=list.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),bw=Math.max(1,maxX-minX),bh=Math.max(1,maxY-minY),sw=420,sh=250,pad=20,s=Math.min((sw-pad*2)/bw,(sh-pad*2)/bh),ox=(sw-bw*s)/2-minX*s,oy=(sh-bh*s)/2-minY*s,d=list.map((p,i)=>`${i?'L':'M'} ${(p.x*s+ox).toFixed(1)} ${(p.y*s+oy).toFixed(1)}`).join(' ')+' Z';return`<svg viewBox="0 0 ${sw} ${sh}" aria-hidden="true"><path class="tdr-rload-track-glow" d="${d}"/><path class="tdr-rload-track-road" d="${d}"/><path class="tdr-rload-track-line" d="${d}"/></svg>`;}
function recent(){try{const a=JSON.parse(localStorage.getItem(RECENT_KEY)||'[]');return Array.isArray(a)?a.slice(-RECENT_LIMIT):[];}catch{return[];}}
function remember(id){try{localStorage.setItem(RECENT_KEY,JSON.stringify([...recent().filter(x=>x!==id),id].slice(-RECENT_LIMIT)));}catch{}}
function chooseTip(m,avoid=''){const used=new Set(recent());let pool=TIPS.filter(t=>!used.has(t.id)&&t.id!==avoid&&(t.mode===m||!t.mode));const contextual=pool.filter(t=>t.mode===m);if(contextual.length&&Math.random()<.42)pool=contextual;if(!pool.length)pool=TIPS.filter(t=>t.id!==avoid);const tip=pool[Math.floor(Math.random()*pool.length)]||TIPS[0];remember(tip.id);return tip;}

function ensureStyle(){if(typeof document==='undefined'||document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
#${ROOT_ID}{position:fixed;inset:0;z-index:2147483200;display:grid;place-items:center;overflow:hidden;background:radial-gradient(circle at 72% 38%,rgba(36,125,159,.18),transparent 31%),radial-gradient(circle at 18% 75%,rgba(255,168,64,.08),transparent 28%),linear-gradient(135deg,#03080e 0%,#07131d 48%,#050b12 100%);color:#f5fbff;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;pointer-events:auto;opacity:1;transition:opacity .24s ease}
#${ROOT_ID}.tdr-rload-out{opacity:0;pointer-events:none}.tdr-rload-shell{position:relative;width:min(94vw,1180px);height:min(88vh,590px);min-height:340px;display:grid;grid-template-columns:minmax(360px,.92fr) minmax(420px,1.08fr);gap:clamp(24px,4vw,58px);align-items:center;padding:clamp(24px,4vw,52px);border:1px solid rgba(106,214,255,.22);background:linear-gradient(145deg,rgba(8,19,29,.96),rgba(4,11,18,.93));box-shadow:0 34px 100px rgba(0,0,0,.52),inset 0 1px rgba(255,255,255,.035);clip-path:polygon(0 18px,18px 0,100% 0,100% calc(100% - 18px),calc(100% - 18px) 100%,0 100%)}
.tdr-rload-shell:before{content:"";position:absolute;left:0;top:0;width:37%;height:3px;background:linear-gradient(90deg,#5fe7ff,rgba(95,231,255,0));box-shadow:0 0 16px rgba(95,231,255,.42)}.tdr-rload-kicker{font-size:10px;font-weight:900;letter-spacing:.22em;color:#64dcfa}.tdr-rload-title{margin-top:8px;font-size:clamp(30px,4.6vw,58px);line-height:.98;font-weight:950;letter-spacing:-.045em}.tdr-rload-sub{margin-top:11px;color:#8fa9ba;font-size:11px;font-weight:800;letter-spacing:.06em}.tdr-rload-car{margin-top:22px;display:grid;grid-template-columns:250px 1fr;align-items:center;gap:18px;min-height:132px;padding:10px 18px;border:1px solid rgba(120,190,220,.17);background:rgba(4,12,19,.62)}.tdr-rload-car-visual{width:250px;height:116px;display:grid;place-items:center;overflow:hidden}.tdr-rload-car img{width:112px;height:210px;object-fit:contain;transform:rotate(90deg) scale(1.02);filter:drop-shadow(0 14px 18px rgba(0,0,0,.58))}.tdr-rload-car small,.tdr-rload-tip small{display:block;color:#7895a8;font-size:10px;font-weight:950;letter-spacing:.16em}.tdr-rload-car strong{display:block;margin-top:6px;font-size:18px;font-weight:950}.tdr-rload-tip{margin-top:18px;padding:15px 17px;border-left:3px solid #ffad47;background:linear-gradient(90deg,rgba(255,173,71,.085),rgba(255,173,71,0));min-height:82px}.tdr-rload-tip small{color:#e1a254}.tdr-rload-tip strong{display:block;margin-top:7px;font-size:clamp(18px,2vw,25px);line-height:1.22;font-weight:900;color:#f7f9fa}.tdr-rload-map{height:min(39vh,275px);min-height:175px;display:grid;place-items:center;border:1px solid rgba(105,214,255,.14);background:radial-gradient(circle at 50% 50%,rgba(41,104,120,.2),rgba(4,11,17,.3) 58%,rgba(2,7,11,.55));overflow:hidden}.tdr-rload-map svg{width:94%;height:94%}.tdr-rload-track-glow{fill:none;stroke:#5ee9ff;stroke-width:18;opacity:.12;filter:blur(5px)}.tdr-rload-track-road{fill:none;stroke:#223b48;stroke-width:12;stroke-linecap:round;stroke-linejoin:round}.tdr-rload-track-line{fill:none;stroke:#ddfbff;stroke-width:3.4;stroke-linecap:round;stroke-linejoin:round}.tdr-rload-map-empty{font-size:42px;font-weight:1000;letter-spacing:.12em;color:#183343}.tdr-rload-phase-row{margin-top:18px;display:flex;justify-content:space-between;align-items:end;gap:16px}.tdr-rload-phase{font-size:13px;font-weight:950;letter-spacing:.11em}.tdr-rload-percent{font:950 24px/1 ui-monospace,SFMono-Regular,Menlo,monospace;color:#66e6ff}.tdr-rload-track{height:6px;margin-top:10px;background:#10232e;overflow:hidden}.tdr-rload-fill{height:100%;width:4%;background:linear-gradient(90deg,#32bfdc,#7df0ff);box-shadow:0 0 14px rgba(95,231,255,.42);transition:width .2s ease}.tdr-rload-steps{display:flex;gap:7px;margin-top:9px}.tdr-rload-steps i{height:3px;flex:1;background:#18313e}.tdr-rload-steps i.on{background:#5fe7ff;box-shadow:0 0 8px rgba(95,231,255,.44)}
@media(max-width:820px),(max-height:500px){.tdr-rload-shell{width:96vw;height:92vh;min-height:290px;grid-template-columns:44% 56%;gap:14px;padding:16px 20px}.tdr-rload-title{font-size:clamp(25px,5.8vw,40px)}.tdr-rload-sub{font-size:9px;margin-top:7px}.tdr-rload-car{margin-top:12px;grid-template-columns:170px 1fr;min-height:90px;padding:6px 10px;gap:8px}.tdr-rload-car-visual{width:170px;height:82px}.tdr-rload-car img{width:80px;height:150px;transform:rotate(90deg) scale(1.02)}.tdr-rload-car small{font-size:8px}.tdr-rload-car strong{font-size:13px}.tdr-rload-tip{margin-top:9px;padding:9px 11px;min-height:56px}.tdr-rload-tip strong{font-size:14px}.tdr-rload-map{height:43vh;min-height:130px}.tdr-rload-phase-row{margin-top:9px}.tdr-rload-phase{font-size:10px}.tdr-rload-percent{font-size:20px}}
`;document.head.appendChild(s);}

function mount(scene){if(typeof document==='undefined')return null;ensureStyle();document.getElementById(ROOT_ID)?.remove?.();const l=lang(),m=mode(),tk=trackKey(scene),cid=carId(scene),tip=chooseTip(m),root=document.createElement('div');root.id=ROOT_ID;root.innerHTML=`<div class="tdr-rload-shell"><div><div class="tdr-rload-kicker">TOP DOWN RACE // ${l==='en'?'RACE PREPARATION':'PREPARACIÓN DE CARRERA'}</div><div class="tdr-rload-title" data-track-name>${trackName(scene,tk,l)}</div><div class="tdr-rload-sub"><span>${modeName(m,l)}</span> · <span data-surface>${surfaceName(scene,tk,l)}</span> · ${quality()}</div><div class="tdr-rload-car"><div class="tdr-rload-car-visual"><img data-car-image src="${BASE}assets/cars/lobby/${encodeURIComponent(cid)}.webp" alt=""></div><span><small>${l==='en'?'SELECTED CAR':'COCHE SELECCIONADO'}</small><strong data-car-name>${carName(scene,cid)}</strong></span></div><div class="tdr-rload-tip"><small data-tip-cat>${l==='en'?tip.catEn:tip.catEs}</small><strong data-tip>${l==='en'?tip.en:tip.es}</strong></div></div><div><div class="tdr-rload-map" data-map>${svg(points(scene,tk))}</div><div class="tdr-rload-phase-row"><div class="tdr-rload-phase" data-phase>${l==='en'?'LOADING RESOURCES':'CARGANDO RECURSOS'}</div><div class="tdr-rload-percent" data-percent>00%</div></div><div class="tdr-rload-track"><div class="tdr-rload-fill" data-fill></div></div><div class="tdr-rload-steps">${'<i></i>'.repeat(6)}</div></div></div>`;document.body.appendChild(root);const ui={root,lang:l,mode:m,trackKey:tk,carId:cid,tipId:tip.id,createdAt:performance.now(),percent:0,done:false,raf:0,tipTimer:0,stableSince:0,loaderCleanup:null,prevTimePaused:false,prevPhysicsPaused:false};ui.tipTimer=window.setInterval(()=>{if(ui.done||!root.isConnected)return;const next=chooseTip(m,ui.tipId);ui.tipId=next.id;const c=root.querySelector('[data-tip-cat]'),t=root.querySelector('[data-tip]');if(c)c.textContent=l==='en'?next.catEn:next.catEs;if(t)t.textContent=l==='en'?next.en:next.es;},TIP_ROTATE_MS);scene._tdrRaceLoadingExperience=ui;return ui;}
function progress(scene,value,phase){const ui=scene?._tdrRaceLoadingExperience;if(!ui?.root?.isConnected||ui.done)return;const p=Math.max(ui.percent,Math.min(100,Math.round(Number(value)||0)));ui.percent=p;const f=ui.root.querySelector('[data-fill]'),n=ui.root.querySelector('[data-percent]'),l=ui.root.querySelector('[data-phase]');if(f)f.style.width=`${Math.max(3,p)}%`;if(n)n.textContent=`${String(p).padStart(2,'0')}%`;if(l&&phase)l.textContent=phase;const steps=[...ui.root.querySelectorAll('.tdr-rload-steps i')],on=Math.ceil(p/100*steps.length);steps.forEach((el,i)=>el.classList.toggle('on',i<on));}
function expectedCells(scene){const c=scene?.track?.geom?.cells;if(!(c instanceof Map))return 0;let n=0;for(const v of c.values())if(v?.polys?.length)n++;return n;}
function ready(scene){const trackReady=!!scene?.track?.geom,envExpected=Array.isArray(scene?._tdrExpectedEnvironmentTextures)&&scene._tdrExpectedEnvironmentTextures.length>0,environmentReady=!envExpected||scene?._tdrEnvironmentReady===true,expected=expectedCells(scene),gfx=scene?.track?.gfxByCell,visualCount=gfx instanceof Map?gfx.size:0,visualReady=expected===0||visualCount>=Math.min(expected,6),carReady=!!(scene?.carBody?.body||scene?.car?.body),hudReady=!!(scene?.raceInfoHud?.scene||scene?.ttHud||scene?.hud||scene?.minimap||scene?.minimapUnifiedPanel?.scene),startReady=!!(scene?._startModal?.scene||scene?._startState);return{trackReady,environmentReady,visualReady,carReady,hudReady,startReady,ready:trackReady&&environmentReady&&visualReady&&carReady&&hudReady&&startReady};}
function freeze(scene,ui){ui.prevTimePaused=!!scene?.time?.paused;ui.prevPhysicsPaused=!!scene?.physics?.world?.isPaused;try{if(scene?.time)scene.time.paused=true;}catch{}try{scene?.physics?.world?.pause?.();}catch{}}
function unfreeze(scene,ui){try{if(scene?.time&&!ui.prevTimePaused)scene.time.paused=false;}catch{}try{if(!ui.prevPhysicsPaused)scene?.physics?.world?.resume?.();}catch{}}
function finish(scene){const ui=scene?._tdrRaceLoadingExperience;if(!ui||ui.done)return;progress(scene,100,ui.lang==='en'?'READY TO RACE':'LISTO PARA CORRER');ui.done=true;unfreeze(scene,ui);window.setTimeout(()=>{try{ui.root?.classList?.add('tdr-rload-out');}catch{}window.setTimeout(()=>{try{ui.root?.remove?.();}catch{}},250);},READY_MIN_MS);}
function gate(scene){const ui=scene?._tdrRaceLoadingExperience;if(!ui)return;freeze(scene,ui);progress(scene,62,ui.lang==='en'?'BUILDING TRACK':'PREPARANDO PISTA');const started=performance.now();const tick=()=>{if(ui.done||!ui.root?.isConnected)return;const r=ready(scene),elapsed=performance.now()-started;if(!r.trackReady)progress(scene,62,ui.lang==='en'?'BUILDING TRACK':'PREPARANDO PISTA');else if(!r.environmentReady)progress(scene,72,ui.lang==='en'?'APPLYING COLLISIONS':'APLICANDO COLISIONES');else if(!r.visualReady)progress(scene,82,ui.lang==='en'?'DRAWING CIRCUIT':'DIBUJANDO CIRCUITO');else if(!r.carReady)progress(scene,88,ui.lang==='en'?'PREPARING CAR':'PREPARANDO COCHE');else if(!r.hudReady)progress(scene,94,ui.lang==='en'?'STARTING HUD':'INICIANDO HUD');else if(!r.startReady)progress(scene,98,ui.lang==='en'?'PREPARING START':'PREPARANDO SALIDA');else progress(scene,99,ui.lang==='en'?'FINAL CHECK':'COMPROBACIÓN FINAL');if(r.ready){if(!ui.stableSince)ui.stableSince=performance.now();if(performance.now()-ui.stableSince>=140){finish(scene);return;}}else ui.stableSince=0;if(elapsed>=READY_TIMEOUT_MS){console.warn('[race-loading] readiness timeout; releasing race',r);finish(scene);return;}ui.raf=requestAnimationFrame(tick);};ui.raf=requestAnimationFrame(tick);}
function cleanup(scene){const ui=scene?._tdrRaceLoadingExperience;if(!ui)return;try{cancelAnimationFrame(ui.raf);}catch{}try{clearInterval(ui.tipTimer);}catch{}try{ui.loaderCleanup?.();}catch{}try{unfreeze(scene,ui);}catch{}try{ui.root?.remove?.();}catch{}scene._tdrRaceLoadingExperience=null;}

export function installRaceLoadingExperience(RaceSceneClass){const proto=RaceSceneClass?.prototype;if(!proto||proto.__tdrRaceLoadingExperienceInstalled)return;const originalPreload=proto.preload;proto.preload=function(...args){const result=originalPreload?.apply(this,args);try{
    // Do NOT call the legacy _destroyRaceLoadingUi here. It also owns recovery
    // behaviour used by the race loader; destroying it during preload can leave
    // Phaser at progress=1 without completing the scene transition.
    const oldEnv=document.getElementById('tdr-track-loading');if(oldEnv)oldEnv.style.visibility='hidden';
    const ui=mount(this);if(ui){const onProgress=p=>{const n=Math.max(0,Math.min(1,Number(p)||0));const complete=n>=.995;progress(this,complete?58:Math.round(n*56),complete?(ui.lang==='en'?'FINALIZING RESOURCES':'FINALIZANDO RECURSOS'):(ui.lang==='en'?'LOADING RESOURCES':'CARGANDO RECURSOS'));};const onError=()=>progress(this,Math.max(12,ui.percent),ui.lang==='en'?'RETRYING RESOURCES':'REINTENTANDO RECURSOS');const onComplete=()=>progress(this,60,ui.lang==='en'?'RESOURCES READY':'RECURSOS LISTOS');this.load?.on?.('progress',onProgress);this.load?.on?.('loaderror',onError);this.load?.once?.('complete',onComplete);ui.loaderCleanup=()=>{try{this.load?.off?.('progress',onProgress);}catch{}try{this.load?.off?.('loaderror',onError);}catch{}try{this.load?.off?.('complete',onComplete);}catch{}};}}
  catch(err){console.warn('[race-loading] preload UI failed',err);}return result;};const originalCreate=proto.create;proto.create=function(...args){let result;try{result=originalCreate?.apply(this,args);}catch(err){console.warn('[race-loading] create failed',err);throw err;}try{this._tdrRaceLoadingExperience?.loaderCleanup?.();this._destroyRaceLoadingUi?.();document.getElementById('tdr-track-loading')?.remove?.();gate(this);}catch(err){console.warn('[race-loading] gate setup failed',err);try{finish(this);}catch{}}const clean=()=>cleanup(this);this.events?.once?.('shutdown',clean);this.events?.once?.('destroy',clean);return result;};proto.__tdrRaceLoadingExperienceInstalled=true;}
