const SESSION_KEY='tdr2:runtimeSession';
const LAST_EVENT_KEY='tdr2:runtimeLastEvent';
const FLIGHT_KEY='tdr2:runtimeFlightRecorder';
const AUTO_SAFE_UNTIL_KEY='tdr2:autoIosSafeModeUntil';
const MAX_FLIGHT_EVENTS=36;
function safeJson(raw){try{return JSON.parse(raw);}catch{return null;}}
function store(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
function isIOSDevice(){try{const ua=String(navigator?.userAgent||''),platform=String(navigator?.platform||'');return /iPhone|iPad|iPod/i.test(ua)||(platform==='MacIntel'&&Number(navigator?.maxTouchPoints||0)>1);}catch{return false;}}
function armAutoSafeMode(){if(!isIOSDevice())return;try{localStorage.setItem(AUTO_SAFE_UNTIL_KEY,String(Date.now()+6*60*60*1000));}catch{}}
function sceneName(game){try{const scenes=game?.scene?.getScenes?.(true)||[];const s=scenes[scenes.length-1];return String(s?.sys?.settings?.key||s?.scene?.key||'unknown');}catch{return'unknown';}}
function sceneState(game){try{return Object.values(game?.scene?.keys||{}).map(s=>({key:String(s?.sys?.settings?.key||''),active:!!s?.sys?.isActive?.(),sleeping:!!s?.sys?.isSleeping?.(),visible:!!s?.sys?.isVisible?.()})).filter(s=>s.key);}catch{return[];}}
function metrics(game){let textureCount=null,domNodes=null,heapUsed=null,heapLimit=null;try{textureCount=Object.keys(game?.textures?.list||{}).length;}catch{}try{domNodes=document.getElementsByTagName('*').length;}catch{}try{heapUsed=Number(performance?.memory?.usedJSHeapSize||0)||null;heapLimit=Number(performance?.memory?.jsHeapSizeLimit||0)||null;}catch{}return{textureCount,domNodes,heapUsed,heapLimit};}
function flight(game,type,extra={}){const entry={at:new Date().toISOString(),ms:Date.now(),type,scene:sceneName(game),...metrics(game),...extra};try{const old=safeJson(localStorage.getItem(FLIGHT_KEY));const list=Array.isArray(old)?old:[];list.push(entry);if(list.length>MAX_FLIGHT_EVENTS)list.splice(0,list.length-MAX_FLIGHT_EVENTS);store(FLIGHT_KEY,list);}catch{}return entry;}
function snapshot(game,type,extra={}){const canvas=game?.canvas,renderer=game?.renderer;const info={at:new Date().toISOString(),type,scene:sceneName(game),mode:(()=>{try{return localStorage.getItem('tdr2:gameMode')||null;}catch{return null;}})(),track:(()=>{try{return localStorage.getItem('tdr2:selectedTrack')||null;}catch{return null;}})(),dpr:Number(window.devicePixelRatio||1),canvasW:Number(canvas?.width||0),canvasH:Number(canvas?.height||0),cssW:Number(canvas?.clientWidth||0),cssH:Number(canvas?.clientHeight||0),renderer:String(renderer?.type??''),scenes:sceneState(game),...metrics(game),...extra};store(LAST_EVENT_KEY,info);flight(game,type,extra);return info;}
function showNotice(info){if(typeof document==='undefined'||!info)return;const old=document.querySelector('[data-tdr-crash-notice]');old?.remove?.();const node=document.createElement('div');node.dataset.tdrCrashNotice='1';node.style.cssText='position:fixed;left:50%;top:12px;transform:translateX(-50%);z-index:25000;max-width:min(92vw,640px);padding:9px 12px;border:1px solid #ff9f43;background:rgba(7,15,24,.96);color:#fff;font:700 11px system-ui,-apple-system,Segoe UI,sans-serif;box-shadow:0 4px 18px #0008;text-align:center;pointer-events:none';const label=info.type==='webglcontextlost'?'WEBGL PERDIÓ EL CONTEXTO':info.type==='js_error'?'ERROR JAVASCRIPT':info.type==='promise_rejection'?'ERROR ASÍNCRONO':'REINICIO INESPERADO';node.textContent=`DIAGNÓSTICO · ${label} · escena ${info.scene||'desconocida'}`;document.body.appendChild(node);setTimeout(()=>node.remove(),9000);}
export function installRuntimeCrashDiagnostics(game){
 if(typeof window==='undefined'||!game||window.__tdrRuntimeCrashDiagnostics)return;window.__tdrRuntimeCrashDiagnostics=true;
 const previous=safeJson((()=>{try{return localStorage.getItem(SESSION_KEY);}catch{return null;}})());if(previous?.active===true&&previous?.clean!==true){const detected={...previous,type:'unexpected_reload',detectedAt:new Date().toISOString()};store(LAST_EVENT_KEY,detected);flight(game,'unexpected_reload',{previousScene:previous.scene||null,lastBeat:previous.lastBeat||null});armAutoSafeMode();setTimeout(()=>showNotice(detected),1200);}
 const session={id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,startedAt:new Date().toISOString(),startedMs:Date.now(),lastBeat:new Date().toISOString(),active:true,clean:false,hadError:false};store(SESSION_KEY,session);flight(game,'session_start');
 let lastScene=sceneName(game),lastTextures=metrics(game).textureCount;
 const beat=()=>{session.lastBeat=new Date().toISOString();session.scene=sceneName(game);const m=metrics(game);session.textureCount=m.textureCount;session.domNodes=m.domNodes;store(SESSION_KEY,session);if(session.scene!==lastScene){flight(game,'scene_change',{from:lastScene,to:session.scene,scenes:sceneState(game)});lastScene=session.scene;}if(Number.isFinite(m.textureCount)&&Number.isFinite(lastTextures)&&m.textureCount-lastTextures>=12){flight(game,'texture_growth',{from:lastTextures,to:m.textureCount});}if(Number.isFinite(m.textureCount))lastTextures=m.textureCount;};
 const timer=setInterval(beat,5000);const onVisibility=()=>flight(game,document.hidden?'hidden':'visible',{scenes:sceneState(game)});
 const onError=(event)=>{session.hadError=true;const info=snapshot(game,'js_error',{message:String(event?.message||'error'),source:String(event?.filename||''),line:Number(event?.lineno||0),column:Number(event?.colno||0)});showNotice(info);};const onRejection=(event)=>{session.hadError=true;const reason=event?.reason;const info=snapshot(game,'promise_rejection',{message:String(reason?.message||reason||'unhandled rejection')});showNotice(info);};const onContextLost=(event)=>{session.hadError=true;try{event?.preventDefault?.();}catch{}const info=snapshot(game,'webglcontextlost');armAutoSafeMode();showNotice(info);};
 const markClean=()=>{session.active=false;session.clean=true;session.endedAt=new Date().toISOString();session.scene=sceneName(game);store(SESSION_KEY,session);flight(game,'clean_exit');if(isIOSDevice()&&!session.hadError&&Date.now()-Number(session.startedMs||Date.now())>=60000){try{localStorage.removeItem(AUTO_SAFE_UNTIL_KEY);}catch{}}};
 window.__tdrGetFlightRecorder=()=>{try{return safeJson(localStorage.getItem(FLIGHT_KEY))||[];}catch{return[];}};window.__tdrClearFlightRecorder=()=>{try{localStorage.removeItem(FLIGHT_KEY);return true;}catch{return false;}};
 window.addEventListener('error',onError);window.addEventListener('unhandledrejection',onRejection);window.addEventListener('pagehide',markClean);window.addEventListener('beforeunload',markClean);document.addEventListener('visibilitychange',onVisibility);game.canvas?.addEventListener?.('webglcontextlost',onContextLost,false);
 game.events?.once?.('destroy',()=>{clearInterval(timer);markClean();window.removeEventListener('error',onError);window.removeEventListener('unhandledrejection',onRejection);window.removeEventListener('pagehide',markClean);window.removeEventListener('beforeunload',markClean);document.removeEventListener('visibilitychange',onVisibility);game.canvas?.removeEventListener?.('webglcontextlost',onContextLost,false);window.__tdrRuntimeCrashDiagnostics=false;});
}
