const SETTINGS_KEY='tdr2:settings';

export const SUPPORTED_LANGUAGES=Object.freeze([
  Object.freeze({code:'es',label:'Español',nativeLabel:'Español'}),
  Object.freeze({code:'en',label:'English',nativeLabel:'English'})
]);

const DICTIONARIES=Object.freeze({
  es:Object.freeze({
    'settings.back':'← VOLVER','settings.title':'CONFIGURACIÓN','settings.saved':'Guardado automático ✓','settings.controls':'CONTROLES','settings.video':'VÍDEO','settings.audio':'AUDIO','settings.language':'IDIOMA','settings.languageTitle':'IDIOMA DEL JUEGO','settings.languageDesc':'Elige el idioma de la interfaz. La selección se guarda en este dispositivo.','settings.languageActive':'Idioma activo','settings.languageNote':'Español e inglés disponibles en la primera versión. Francés, alemán e italiano quedan preparados para una actualización posterior.','settings.restartNote':'Los textos de otras pantallas usarán el nuevo idioma al volver a entrar en ellas.','settings.customizeControls':'PERSONALIZAR CONTROLES','settings.cancel':'← CANCELAR','settings.reset':'RESTABLECER','settings.cleanView':'VISTA LIMPIA','settings.save':'GUARDAR','settings.savedShort':'GUARDADO ✓',
    'lobby.coins':'MONEDAS','lobby.inventory':'INVENTARIO','lobby.store':'TIENDA','lobby.settings':'CONFIGURACIÓN','lobby.play':'ARRANCAR MOTOR','lobby.garage':'GARAJE','lobby.factory':'FÁBRICA','lobby.tracks':'CIRCUITOS','lobby.mainActions':'Acciones principales','lobby.mainNav':'Navegación principal','lobby.trackLayout':'Trazado del circuito','lobby.selectedCar':'COCHE SELECCIONADO','lobby.selectedTrack':'CIRCUITO SELECCIONADO','lobby.length':'LONGITUD','lobby.sectors':'SECTORES','lobby.surface':'SUPERFICIE','lobby.direction':'SENTIDO','lobby.asphalt':'ASFALTO','lobby.dirt':'TIERRA','lobby.clockwise':'HORARIO','lobby.counterclockwise':'ANTIHORARIO','lobby.seasonComplete':'TEMPORADA COMPLETADA','lobby.eliteDriver':'PILOTO DE ÉLITE','lobby.completedSeven':'HAS COMPLETADO LOS 7 EVENTOS DE PROGRESIÓN','lobby.eventsCount':'7/7 EVENTOS','lobby.eventComplete':'EVENTO COMPLETADO','lobby.event':'EVENTO {current}/{total}','lobby.reward':'PREMIO · {reward}','lobby.claimReward':'RECLAMAR PREMIO',
    'events.first-stint.title':'PRIMER STINT','events.first-stint.desc':'Completa 5 vueltas en cualquier circuito.','events.clean-lines.title':'TRAZADA LIMPIA','events.clean-lines.desc':'Completa 8 vueltas sin penalizaciones.','events.track-tour.title':'CONOCE EL PADDOCK','events.track-tour.desc':'Da 3 vueltas en 3 circuitos diferentes.','events.race-rhythm.title':'RITMO DE CARRERA','events.race-rhythm.desc':'Encadena 15 vueltas limpias.','events.endurance.title':'RESISTENCIA','events.endurance.desc':'Completa 30 vueltas desde la activación.','events.circuit-master.title':'DOMINIO DE CIRCUITOS','events.circuit-master.desc':'Da 5 vueltas en 5 circuitos diferentes.','events.pro-driver.title':'PILOTO PRO','events.pro-driver.desc':'Completa 50 vueltas limpias.','events.label.laps':'VUELTAS','events.label.cleanLaps':'VUELTAS LIMPIAS','events.label.tracks':'CIRCUITOS','events.label.progress':'PROGRESO','events.coins':'MONEDAS','events.more':'MÁS','items.scrap':'Chatarra','items.alloy':'Aleación','items.rubber':'Goma','items.compound':'Compuesto','items.disc':'Disco','items.spring':'Muelle','items.gear':'Engranaje','items.ecu':'ECU'
  }),
  en:Object.freeze({
    'settings.back':'← BACK','settings.title':'SETTINGS','settings.saved':'Autosaved ✓','settings.controls':'CONTROLS','settings.video':'VIDEO','settings.audio':'AUDIO','settings.language':'LANGUAGE','settings.languageTitle':'GAME LANGUAGE','settings.languageDesc':'Choose the interface language. Your selection is saved on this device.','settings.languageActive':'Active language','settings.languageNote':'Spanish and English are available for the first release. French, German and Italian are ready to be added in a later update.','settings.restartNote':'Other screens will use the new language the next time you open them.','settings.customizeControls':'CUSTOMIZE CONTROLS','settings.cancel':'← CANCEL','settings.reset':'RESET','settings.cleanView':'CLEAN VIEW','settings.save':'SAVE','settings.savedShort':'SAVED ✓',
    'lobby.coins':'COINS','lobby.inventory':'INVENTORY','lobby.store':'STORE','lobby.settings':'SETTINGS','lobby.play':'START ENGINE','lobby.garage':'GARAGE','lobby.factory':'FACTORY','lobby.tracks':'TRACKS','lobby.mainActions':'Main actions','lobby.mainNav':'Main navigation','lobby.trackLayout':'Track layout','lobby.selectedCar':'SELECTED CAR','lobby.selectedTrack':'SELECTED TRACK','lobby.length':'LENGTH','lobby.sectors':'SECTORS','lobby.surface':'SURFACE','lobby.direction':'DIRECTION','lobby.asphalt':'ASPHALT','lobby.dirt':'DIRT','lobby.clockwise':'CLOCKWISE','lobby.counterclockwise':'COUNTERCLOCKWISE','lobby.seasonComplete':'SEASON COMPLETE','lobby.eliteDriver':'ELITE DRIVER','lobby.completedSeven':'YOU COMPLETED ALL 7 PROGRESSION EVENTS','lobby.eventsCount':'7/7 EVENTS','lobby.eventComplete':'EVENT COMPLETE','lobby.event':'EVENT {current}/{total}','lobby.reward':'REWARD · {reward}','lobby.claimReward':'CLAIM REWARD',
    'events.first-stint.title':'FIRST STINT','events.first-stint.desc':'Complete 5 laps on any track.','events.clean-lines.title':'CLEAN LINE','events.clean-lines.desc':'Complete 8 laps without penalties.','events.track-tour.title':'PADDOCK TOUR','events.track-tour.desc':'Complete 3 laps on 3 different tracks.','events.race-rhythm.title':'RACE RHYTHM','events.race-rhythm.desc':'String together 15 clean laps.','events.endurance.title':'ENDURANCE','events.endurance.desc':'Complete 30 laps from activation.','events.circuit-master.title':'TRACK MASTERY','events.circuit-master.desc':'Complete 5 laps on 5 different tracks.','events.pro-driver.title':'PRO DRIVER','events.pro-driver.desc':'Complete 50 clean laps.','events.label.laps':'LAPS','events.label.cleanLaps':'CLEAN LAPS','events.label.tracks':'TRACKS','events.label.progress':'PROGRESS','events.coins':'COINS','events.more':'MORE','items.scrap':'Scrap','items.alloy':'Alloy','items.rubber':'Rubber','items.compound':'Compound','items.disc':'Disc','items.spring':'Spring','items.gear':'Gear','items.ecu':'ECU'
  })
});

function normalizeLanguage(value){const code=String(value||'').trim().toLowerCase().split('-')[0];return SUPPORTED_LANGUAGES.some(x=>x.code===code)?code:null;}
export function detectDeviceLanguage(){try{const candidates=[navigator?.language,...(navigator?.languages||[])];for(const candidate of candidates){const code=normalizeLanguage(candidate);if(code)return code;}}catch{}return 'en';}
export function getLanguage(){try{const settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');return normalizeLanguage(settings?.language)||detectDeviceLanguage();}catch{return detectDeviceLanguage();}}
export function setLanguage(language){const code=normalizeLanguage(language)||'en';try{const settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');settings.language=code;localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{}try{document.documentElement.lang=code;}catch{}try{window.dispatchEvent(new CustomEvent('tdr2:language-change',{detail:{language:code}}));}catch{}return code;}
export function t(key,params=null,language=getLanguage()){const lang=normalizeLanguage(language)||'en';const source=DICTIONARIES[lang]||DICTIONARIES.en;let value=source[key]??DICTIONARIES.en[key]??key;if(params&&typeof value==='string'){for(const [name,replacement] of Object.entries(params)){value=value.replaceAll(`{${name}}`,String(replacement));}}return value;}
export function languageName(code){return SUPPORTED_LANGUAGES.find(x=>x.code===normalizeLanguage(code))?.nativeLabel||'English';}
export function initLanguage(){const language=getLanguage();try{document.documentElement.lang=language;}catch{}return language;}
