const SETTINGS_KEY='tdr2:settings';

export const SUPPORTED_LANGUAGES=Object.freeze([
  Object.freeze({code:'es',label:'Español',nativeLabel:'Español'}),
  Object.freeze({code:'en',label:'English',nativeLabel:'English'})
]);

const DICTIONARIES=Object.freeze({
  es:Object.freeze({
    'settings.back':'← VOLVER','settings.title':'CONFIGURACIÓN','settings.saved':'Guardado automático ✓','settings.controls':'CONTROLES','settings.video':'VÍDEO','settings.audio':'AUDIO','settings.language':'IDIOMA','settings.languageTitle':'IDIOMA DEL JUEGO','settings.languageDesc':'Elige el idioma de la interfaz. La selección se guarda en este dispositivo.','settings.languageActive':'Idioma activo','settings.languageNote':'Español e inglés disponibles en la primera versión. Francés, alemán e italiano quedan preparados para una actualización posterior.','settings.restartNote':'Los textos de otras pantallas usarán el nuevo idioma al volver a entrar en ellas.','settings.customizeControls':'PERSONALIZAR CONTROLES','settings.cancel':'← CANCELAR','settings.reset':'RESTABLECER','settings.cleanView':'VISTA LIMPIA','settings.save':'GUARDAR','settings.savedShort':'GUARDADO ✓',
    'lobby.coins':'MONEDAS','lobby.inventory':'INVENTARIO','lobby.store':'TIENDA','lobby.settings':'CONFIGURACIÓN','lobby.play':'ARRANCAR MOTOR','lobby.garage':'GARAJE','lobby.factory':'FÁBRICA','lobby.tracks':'CIRCUITOS','lobby.mainActions':'Acciones principales','lobby.mainNav':'Navegación principal','lobby.trackLayout':'Trazado del circuito','lobby.selectedCar':'COCHE SELECCIONADO','lobby.selectedTrack':'CIRCUITO SELECCIONADO','lobby.length':'LONGITUD','lobby.sectors':'SECTORES','lobby.surface':'SUPERFICIE','lobby.direction':'SENTIDO','lobby.asphalt':'ASFALTO','lobby.dirt':'TIERRA','lobby.clockwise':'HORARIO','lobby.counterclockwise':'ANTIHORARIO','lobby.seasonComplete':'TEMPORADA COMPLETADA','lobby.eliteDriver':'PILOTO DE ÉLITE','lobby.completedSeven':'HAS COMPLETADO LOS 7 EVENTOS DE PROGRESIÓN','lobby.eventsCount':'7/7 EVENTOS','lobby.eventComplete':'EVENTO COMPLETADO','lobby.event':'EVENTO {current}/{total}','lobby.reward':'PREMIO · {reward}','lobby.claimReward':'RECLAMAR PREMIO',
    'events.first-stint.title':'PRIMER STINT','events.first-stint.desc':'Completa 5 vueltas en cualquier circuito.','events.clean-lines.title':'TRAZADA LIMPIA','events.clean-lines.desc':'Completa 8 vueltas sin penalizaciones.','events.track-tour.title':'CONOCE EL PADDOCK','events.track-tour.desc':'Da 3 vueltas en 3 circuitos diferentes.','events.race-rhythm.title':'RITMO DE CARRERA','events.race-rhythm.desc':'Encadena 15 vueltas limpias.','events.endurance.title':'RESISTENCIA','events.endurance.desc':'Completa 30 vueltas desde la activación.','events.circuit-master.title':'DOMINIO DE CIRCUITOS','events.circuit-master.desc':'Da 5 vueltas en 5 circuitos diferentes.','events.pro-driver.title':'PILOTO PRO','events.pro-driver.desc':'Completa 50 vueltas limpias.','events.label.laps':'VUELTAS','events.label.cleanLaps':'VUELTAS LIMPIAS','events.label.tracks':'CIRCUITOS','events.label.progress':'PROGRESO','events.coins':'MONEDAS','events.more':'MÁS','items.scrap':'Chatarra','items.alloy':'Aleación','items.rubber':'Goma','items.compound':'Compuesto','items.disc':'Disco','items.spring':'Muelle','items.gear':'Engranaje','items.ecu':'ECU',
    'garage.title':'GARAJE','garage.collection':'COLECCIÓN','garage.player':'PLAYER','garage.admin':'ADMIN','garage.editCar':'EDITAR COCHE','garage.select':'SELECCIONAR','garage.back':'VOLVER','garage.viewSpecs':'VER FICHA','garage.topSpeed':'VEL PUNTA','garage.acceleration':'ACELERACIÓN','garage.braking':'FRENADA',
    'garage.personality.helix_spark':'Facilísimo y predecible. Su límite llega pronto: perfecto para aprender, enseguida querrás hacerlo correr más.','garage.personality.helix_comet':'Sumamente divertido y permisivo. Mantiene el ADN HÉLIX, pero ya invita a buscar ritmo en cada curva.','garage.personality.helix_pulse':'Muy fácil de llevar y magnífico al salir de curva. Rápido, limpio y con una respuesta que engancha.','garage.personality.crown_axis':'Refinado y muy accesible. Hace fácil ir deprisa y transmite control desde las primeras curvas.','garage.personality.crown_vector':'Fluido y progresivo. Te deja construir la vuelta y cada décima aparece cuando entiendes mejor la trazada.','garage.personality.crown_equinox':'Potencia seria con riesgo real. Cuando lo clavas vuela; si te pasas, te recuerda enseguida dónde está el límite.','garage.personality.avenir_gripline':'Mucho control y bastante velocidad. Preciso de morro, inspira confianza y coloca el coche donde se lo pides.','garage.personality.avenir_apex':'Nervioso al principio, pero se deja domar rápido. Exige atención y recompensa enseguida cuando entiendes su giro.','garage.personality.avenir_torque':'Sublime: se come los pianos como un poseso y parece ir por raíles. Potente al salir y muy veloz cuando estira.','garage.personality.veloce_flash':'Rápido y exigente. La trasera se mueve mucho y obliga a frenar de verdad antes de atacar la salida.','garage.personality.veloce_surge':'Más salvaje que el Flash. Hay que orientar bien el coche antes de abrir gas o la pista se acaba muy deprisa.','garage.personality.veloce_photon':'Potro indomable. Aceleración de otro planeta y cero paciencia con una mala colocación: dominarlo es parte del premio.','garage.personality.forge_hammer':'Tremendamente complicado y muy peculiar. Se va incluso a poca velocidad, aunque la hierba apenas castiga sus excesos.','garage.personality.forge_anvil':'Brutal en las chicanes: exige casi parar para reorientarlo. El gas a pequeños empujones es la clave para domarlo.','garage.personality.forge_colossus':'Un gigante que pide peso y anticipación. Si lo fuerzas, el morro tiembla y la zaga baila mucho más de lo esperado.',
    'modes.title':'ELIGE MODO DE JUEGO','modes.swipe':'Desliza el carrusel o usa las flechas','modes.lastUsed':'ÚLTIMO USADO','modes.duelDistance':'🏎️ DUELO · DISTANCIA','modes.duelDesc':'Elige la duración del duelo contra CPU1','modes.laps':'{laps} VUELTAS','modes.cancel':'CANCELAR',
    'inventory.title':'INVENTARIO','inventory.materials':'MATERIALES','inventory.parts':'PIEZAS','inventory.coins':'◈ {coins} MONEDAS','inventory.noTierParts':'NO TIENES PIEZAS {tier} EN EL INVENTARIO','inventory.noParts':'AÚN NO TIENES PIEZAS\n\nFabrícalas en FACTORY y aparecerán aquí.','inventory.uninstall':'DESINSTALAR','inventory.install':'INSTALAR · ×{qty}',
    'tracks.length':'LONGITUD','tracks.sectors':'SECTORES','tracks.surface':'SUPERFICIE','tracks.width':'ANCHO','tracks.select':'SELECCIONAR','tracks.edit':'EDITAR'
  }),
  en:Object.freeze({
    'settings.back':'← BACK','settings.title':'SETTINGS','settings.saved':'Autosaved ✓','settings.controls':'CONTROLS','settings.video':'VIDEO','settings.audio':'AUDIO','settings.language':'LANGUAGE','settings.languageTitle':'GAME LANGUAGE','settings.languageDesc':'Choose the interface language. Your selection is saved on this device.','settings.languageActive':'Active language','settings.languageNote':'Spanish and English are available for the first release. French, German and Italian are ready to be added in a later update.','settings.restartNote':'Other screens will use the new language the next time you open them.','settings.customizeControls':'CUSTOMIZE CONTROLS','settings.cancel':'← CANCEL','settings.reset':'RESET','settings.cleanView':'CLEAN VIEW','settings.save':'SAVE','settings.savedShort':'SAVED ✓',
    'lobby.coins':'COINS','lobby.inventory':'INVENTORY','lobby.store':'STORE','lobby.settings':'SETTINGS','lobby.play':'START ENGINE','lobby.garage':'GARAGE','lobby.factory':'FACTORY','lobby.tracks':'TRACKS','lobby.mainActions':'Main actions','lobby.mainNav':'Main navigation','lobby.trackLayout':'Track layout','lobby.selectedCar':'SELECTED CAR','lobby.selectedTrack':'SELECTED TRACK','lobby.length':'LENGTH','lobby.sectors':'SECTORS','lobby.surface':'SURFACE','lobby.direction':'DIRECTION','lobby.asphalt':'ASPHALT','lobby.dirt':'DIRT','lobby.clockwise':'CLOCKWISE','lobby.counterclockwise':'COUNTERCLOCKWISE','lobby.seasonComplete':'SEASON COMPLETE','lobby.eliteDriver':'ELITE DRIVER','lobby.completedSeven':'YOU COMPLETED ALL 7 PROGRESSION EVENTS','lobby.eventsCount':'7/7 EVENTS','lobby.eventComplete':'EVENT COMPLETE','lobby.event':'EVENT {current}/{total}','lobby.reward':'REWARD · {reward}','lobby.claimReward':'CLAIM REWARD',
    'events.first-stint.title':'FIRST STINT','events.first-stint.desc':'Complete 5 laps on any track.','events.clean-lines.title':'CLEAN LINE','events.clean-lines.desc':'Complete 8 laps without penalties.','events.track-tour.title':'PADDOCK TOUR','events.track-tour.desc':'Complete 3 laps on 3 different tracks.','events.race-rhythm.title':'RACE RHYTHM','events.race-rhythm.desc':'String together 15 clean laps.','events.endurance.title':'ENDURANCE','events.endurance.desc':'Complete 30 laps from activation.','events.circuit-master.title':'TRACK MASTERY','events.circuit-master.desc':'Complete 5 laps on 5 different tracks.','events.pro-driver.title':'PRO DRIVER','events.pro-driver.desc':'Complete 50 clean laps.','events.label.laps':'LAPS','events.label.cleanLaps':'CLEAN LAPS','events.label.tracks':'TRACKS','events.label.progress':'PROGRESS','events.coins':'COINS','events.more':'MORE','items.scrap':'Scrap','items.alloy':'Alloy','items.rubber':'Rubber','items.compound':'Compound','items.disc':'Disc','items.spring':'Spring','items.gear':'Gear','items.ecu':'ECU',
    'garage.title':'GARAGE','garage.collection':'COLLECTION','garage.player':'PLAYER','garage.admin':'ADMIN','garage.editCar':'EDIT CAR','garage.select':'SELECT','garage.back':'BACK','garage.viewSpecs':'VIEW SPECS','garage.topSpeed':'TOP SPEED','garage.acceleration':'ACCELERATION','garage.braking':'BRAKING',
    'garage.personality.helix_spark':'Extremely easy and predictable. Its limit arrives early: perfect for learning, and soon you will want more speed.','garage.personality.helix_comet':'Very playful and forgiving. It keeps the HÉLIX DNA while inviting you to chase more pace through every corner.','garage.personality.helix_pulse':'Easy to drive and excellent on corner exit. Fast, clean and immediately rewarding.','garage.personality.crown_axis':'Refined and approachable. It makes speed feel easy and gives confidence from the first corners.','garage.personality.crown_vector':'Smooth and progressive. It lets you build the lap, finding tenths as you understand the racing line.','garage.personality.crown_equinox':'Serious power with real risk. Nail it and it flies; overdo it and the limit arrives quickly.','garage.personality.avenir_gripline':'Plenty of control and strong speed. Precise at the front, confidence inspiring and easy to place.','garage.personality.avenir_apex':'Nervous at first but quick to tame. It demands attention and rewards you once you understand its turn-in.','garage.personality.avenir_torque':'Sublime over curbs and almost rail-like. Strong on exit and very fast once it stretches its legs.','garage.personality.veloce_flash':'Fast and demanding. The rear moves a lot, forcing proper braking before attacking the exit.','garage.personality.veloce_surge':'Wilder than the Flash. Point it correctly before opening the throttle or the track disappears very quickly.','garage.personality.veloce_photon':'An untamed beast. Otherworldly acceleration and no patience for bad positioning; mastering it is part of the reward.','garage.personality.forge_hammer':'Extremely difficult and distinctive. It slides even at low speed, although grass barely punishes its excesses.','garage.personality.forge_anvil':'Brutal through chicanes: it nearly needs to stop before changing direction. Small throttle inputs are the key.','garage.personality.forge_colossus':'A giant that demands anticipation. Force it and the nose shakes while the rear moves far more than expected.',
    'modes.title':'CHOOSE GAME MODE','modes.swipe':'Swipe the carousel or use the arrows','modes.lastUsed':'LAST USED','modes.duelDistance':'🏎️ DUEL · DISTANCE','modes.duelDesc':'Choose the duel length against CPU1','modes.laps':'{laps} LAPS','modes.cancel':'CANCEL',
    'inventory.title':'INVENTORY','inventory.materials':'MATERIALS','inventory.parts':'PARTS','inventory.coins':'◈ {coins} COINS','inventory.noTierParts':'YOU HAVE NO TIER {tier} PARTS IN INVENTORY','inventory.noParts':'YOU HAVE NO PARTS YET\n\nCraft them in FACTORY and they will appear here.','inventory.uninstall':'UNINSTALL','inventory.install':'INSTALL · ×{qty}',
    'tracks.length':'LENGTH','tracks.sectors':'SECTORS','tracks.surface':'SURFACE','tracks.width':'WIDTH','tracks.select':'SELECT','tracks.edit':'EDIT'
  })
});

function normalizeLanguage(value){const code=String(value||'').trim().toLowerCase().split('-')[0];return SUPPORTED_LANGUAGES.some(x=>x.code===code)?code:null;}
export function detectDeviceLanguage(){try{const candidates=[navigator?.language,...(navigator?.languages||[])];for(const candidate of candidates){const code=normalizeLanguage(candidate);if(code)return code;}}catch{}return 'en';}
export function getLanguage(){try{const settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');return normalizeLanguage(settings?.language)||detectDeviceLanguage();}catch{return detectDeviceLanguage();}}
export function setLanguage(language){const code=normalizeLanguage(language)||'en';try{const settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');settings.language=code;localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{}try{document.documentElement.lang=code;}catch{}try{window.dispatchEvent(new CustomEvent('tdr2:language-change',{detail:{language:code}}));}catch{}return code;}
export function t(key,params=null,language=getLanguage()){const lang=normalizeLanguage(language)||'en';const source=DICTIONARIES[lang]||DICTIONARIES.en;let value=source[key]??DICTIONARIES.en[key]??key;if(params&&typeof value==='string'){for(const [name,replacement] of Object.entries(params)){value=value.replaceAll(`{${name}}`,String(replacement));}}return value;}
export function languageName(code){return SUPPORTED_LANGUAGES.find(x=>x.code===normalizeLanguage(code))?.nativeLabel||'English';}
export function initLanguage(){const language=getLanguage();try{document.documentElement.lang=language;}catch{}return language;}
