const EXTRA=Object.freeze({
  es:Object.freeze({
    'common.back':'VOLVER','common.close':'CERRAR','common.cancel':'CANCELAR','common.select':'SELECCIONAR','common.selected':'SELECCIONADO','common.edit':'EDITAR','common.continue':'CONTINUAR','common.results':'RESULTADOS','common.report':'INFORME','common.best':'MEJOR','common.lap':'VUELTA','common.laps':'VUELTAS','common.total':'TOTAL','common.time':'TIEMPO','common.speed':'VELOCIDAD','common.position':'POSICIÓN','common.penalty':'PENALIZACIÓN','common.yes':'SÍ','common.no':'NO',
    'track.atlantic':'CIRCUITO ATLÁNTICO','track.generic':'Circuito','car.generic':'Coche',
    'race.emptySession':'Aún no hay vueltas completas en esta sesión.','race.lapsSectors':'Vueltas · Sectores','race.bestSession':'MEJOR DE LA SESIÓN','race.sectorRecord':'RÉCORD DE SECTOR','race.bestSessionShort':'MEJOR SESIÓN','race.sectorRecordShort':'RÉCORD SECTOR','race.noTimedLaps':'No hay vueltas cronometradas.',
    'race.sessionFinished':'SESIÓN FINALIZADA','race.chestLaps':'COFRE DE {laps} VUELTAS','race.sessionLoot':'BOTÍN DE LA SESIÓN','race.sessionLootDesc':'Todo lo conseguido durante la tanda se entrega junto.','race.level':'NIVEL {level}','race.tapOpen':'TOCA PARA ABRIR','race.materialRewards':'8 MATERIALES · RECOMPENSAS TOTALES','race.pieces':'{count} PIEZAS','race.rewardedLaps':'🏁 {laps} VUELTAS PREMIADAS','race.bonus':'⚡ {laps} BONUS','race.chest':'▣ COFRE {laps}','race.viewResults':'VER RESULTADOS','race.viewReport':'VER INFORME',
    'race.survivalSessionInfo':'INFO DE SESIÓN · SUPERVIVENCIA','race.result':'resultado','race.champion':'1º / CAMPEÓN','race.eliminated':'ELIMINADO','race.rounds':'RONDAS','race.best':'MEJOR','race.average':'MEDIA','race.laps':'VUELTAS','race.worst':'PEOR','race.startingCars':'COCHES INICIALES','race.backResult':'VOLVER AL RESULTADO',
    'race.pause':'PAUSA','race.paused':'PAUSADO','race.resume':'REANUDAR','race.restart':'REINICIAR','race.exit':'SALIR','race.standings':'CLASIFICACIÓN','race.finish':'META','race.start':'SALIDA','race.newRecord':'NUEVO RÉCORD','race.record':'RÉCORD','race.practice':'PRÁCTICA','race.timeAttack':'CONTRARRELOJ','race.ghost':'FANTASMA','race.survival':'SUPERVIVENCIA','race.duel':'DUELO','race.practiceArea':'ÁREA DE PRUEBAS',
    'workshop.title':'TDR WORKSHOP','workshop.flowTop':'1 · CONSIGUE  →  2 · FUSIONA  →  3 · GUARDA  →  4 · EQUIPA','workshop.storage':'1 · ALMACÉN','workshop.storageDesc':'Todo lo que fabricas aparece aquí, en la pestaña PIEZAS.','workshop.materials':'MATERIALES','workshop.parts':'PIEZAS','workshop.new':'NUEVA','workshop.equipped':'EQUIPADA','workshop.equip':'EQUIPAR','workshop.emptyParts':'AÚN NO HAS FABRICADO PIEZAS\n\nFusiona materiales en el banco central.','workshop.bench':'2 · BANCO DE FUSIÓN','workshop.benchDesc':'Toca dos materiales del almacén.\nSi existe receta, verás el resultado antes de fabricar.','workshop.result':'RESULTADO  →  {result}','workshop.craftPart':'FABRICAR PIEZA','workshop.selectRecipe':'SELECCIONA UNA RECETA','workshop.examples':'EJEMPLOS','workshop.doubleLoot':'▶ DUPLICAR ÚLTIMO BOTÍN','workshop.loadout':'3 · COCHE / MONTAJE','workshop.loadoutDesc':'Las piezas fabricadas se equipan desde ALMACÉN → PIEZAS.','workshop.noPart':'SIN PIEZA EQUIPADA','workshop.flow':'FLUJO\nFABRICAR → se guarda en PIEZAS → pulsa EQUIPAR → aparece aquí','workshop.select':'Selecciona','workshop.doubleLootTitle':'DUPLICAR BOTÍN','workshop.lootDoubled':'Botín duplicado','workshop.alreadyClaimed':'Ya reclamado','workshop.pickTwo':'Selecciona dos materiales','workshop.crafted':'FABRICADO · {item} · guardado en {bucket}','workshop.upgrade':'EVOLUCIÓN · {item}','workshop.installed':'{item} equipada en {family}',
    'family.engine':'MOTOR','family.brakes':'FRENOS','family.tires':'RUEDAS','family.suspension':'SUSPENSIÓN','family.transmission':'CAJA',
    'store.title':'TIENDA','store.buy':'COMPRAR','store.owned':'EN PROPIEDAD','store.coins':'MONEDAS','store.notEnough':'MONEDAS INSUFICIENTES','store.close':'CERRAR'
  }),
  en:Object.freeze({
    'common.back':'BACK','common.close':'CLOSE','common.cancel':'CANCEL','common.select':'SELECT','common.selected':'SELECTED','common.edit':'EDIT','common.continue':'CONTINUE','common.results':'RESULTS','common.report':'REPORT','common.best':'BEST','common.lap':'LAP','common.laps':'LAPS','common.total':'TOTAL','common.time':'TIME','common.speed':'SPEED','common.position':'POSITION','common.penalty':'PENALTY','common.yes':'YES','common.no':'NO',
    'track.atlantic':'ATLANTIC CIRCUIT','track.generic':'Track','car.generic':'Car',
    'race.emptySession':'No completed laps in this session yet.','race.lapsSectors':'Laps · Sectors','race.bestSession':'SESSION BEST','race.sectorRecord':'SECTOR RECORD','race.bestSessionShort':'SESSION BEST','race.sectorRecordShort':'SECTOR RECORD','race.noTimedLaps':'No timed laps.',
    'race.sessionFinished':'SESSION COMPLETE','race.chestLaps':'{laps}-LAP CHEST','race.sessionLoot':'SESSION LOOT','race.sessionLootDesc':'Everything earned during the stint is delivered together.','race.level':'LEVEL {level}','race.tapOpen':'TAP TO OPEN','race.materialRewards':'8 MATERIALS · TOTAL REWARDS','race.pieces':'{count} ITEMS','race.rewardedLaps':'🏁 {laps} REWARDED LAPS','race.bonus':'⚡ {laps} BONUS','race.chest':'▣ CHEST {laps}','race.viewResults':'VIEW RESULTS','race.viewReport':'VIEW REPORT',
    'race.survivalSessionInfo':'SESSION INFO · SURVIVAL','race.result':'result','race.champion':'1ST / CHAMPION','race.eliminated':'ELIMINATED','race.rounds':'ROUNDS','race.best':'BEST','race.average':'AVERAGE','race.laps':'LAPS','race.worst':'WORST','race.startingCars':'STARTING CARS','race.backResult':'BACK TO RESULT',
    'race.pause':'PAUSE','race.paused':'PAUSED','race.resume':'RESUME','race.restart':'RESTART','race.exit':'EXIT','race.standings':'STANDINGS','race.finish':'FINISH','race.start':'START','race.newRecord':'NEW RECORD','race.record':'RECORD','race.practice':'PRACTICE','race.timeAttack':'TIME ATTACK','race.ghost':'GHOST','race.survival':'SURVIVAL','race.duel':'DUEL','race.practiceArea':'PRACTICE AREA',
    'workshop.title':'TDR WORKSHOP','workshop.flowTop':'1 · COLLECT  →  2 · COMBINE  →  3 · STORE  →  4 · EQUIP','workshop.storage':'1 · STORAGE','workshop.storageDesc':'Everything you craft appears here under PARTS.','workshop.materials':'MATERIALS','workshop.parts':'PARTS','workshop.new':'NEW','workshop.equipped':'EQUIPPED','workshop.equip':'EQUIP','workshop.emptyParts':'YOU HAVE NOT CRAFTED ANY PARTS YET\n\nCombine materials at the central bench.','workshop.bench':'2 · CRAFTING BENCH','workshop.benchDesc':'Tap two materials from storage.\nIf a recipe exists, you will see the result before crafting.','workshop.result':'RESULT  →  {result}','workshop.craftPart':'CRAFT PART','workshop.selectRecipe':'SELECT A RECIPE','workshop.examples':'EXAMPLES','workshop.doubleLoot':'▶ DOUBLE LAST LOOT','workshop.loadout':'3 · CAR / LOADOUT','workshop.loadoutDesc':'Crafted parts are equipped from STORAGE → PARTS.','workshop.noPart':'NO PART EQUIPPED','workshop.flow':'FLOW\nCRAFT → stored in PARTS → tap EQUIP → appears here','workshop.select':'Select','workshop.doubleLootTitle':'DOUBLE LOOT','workshop.lootDoubled':'Loot doubled','workshop.alreadyClaimed':'Already claimed','workshop.pickTwo':'Select two materials','workshop.crafted':'CRAFTED · {item} · stored in {bucket}','workshop.upgrade':'UPGRADE · {item}','workshop.installed':'{item} equipped in {family}',
    'family.engine':'ENGINE','family.brakes':'BRAKES','family.tires':'TIRES','family.suspension':'SUSPENSION','family.transmission':'GEARBOX',
    'store.title':'STORE','store.buy':'BUY','store.owned':'OWNED','store.coins':'COINS','store.notEnough':'NOT ENOUGH COINS','store.close':'CLOSE'
  })
});

export function extraTranslation(language,key){
  const lang=String(language||'en').toLowerCase().startsWith('es')?'es':'en';
  return EXTRA[lang]?.[key];
}
