const EXTRA=Object.freeze({
  es:Object.freeze({
    'common.back':'VOLVER','common.close':'CERRAR','common.cancel':'CANCELAR','common.select':'SELECCIONAR','common.selected':'SELECCIONADO','common.edit':'EDITAR','common.continue':'CONTINUAR','common.results':'RESULTADOS','common.report':'INFORME','common.best':'MEJOR','common.lap':'VUELTA','common.laps':'VUELTAS','common.total':'TOTAL','common.time':'TIEMPO','common.speed':'VELOCIDAD','common.position':'POSICIÓN','common.penalty':'PENALIZACIÓN','common.yes':'SÍ','common.no':'NO',
    'track.atlantic':'CIRCUITO ATLÁNTICO','track.generic':'Circuito','car.generic':'Coche',
    'race.emptySession':'Aún no hay vueltas completas en esta sesión.','race.lapsSectors':'Vueltas · Sectores','race.bestSession':'MEJOR DE LA SESIÓN','race.sectorRecord':'RÉCORD DE SECTOR','race.bestSessionShort':'MEJOR SESIÓN','race.sectorRecordShort':'RÉCORD SECTOR','race.noTimedLaps':'No hay vueltas cronometradas.',
    'race.sessionFinished':'SESIÓN FINALIZADA','race.chestLaps':'COFRE DE {laps} VUELTAS','race.sessionLoot':'BOTÍN DE LA SESIÓN','race.sessionLootDesc':'Todo lo conseguido durante la tanda se entrega junto.','race.level':'NIVEL {level}','race.tapOpen':'TOCA PARA ABRIR','race.materialRewards':'8 MATERIALES · RECOMPENSAS TOTALES','race.pieces':'{count} PIEZAS','race.rewardedLaps':'🏁 {laps} VUELTAS PREMIADAS','race.bonus':'⚡ {laps} BONUS','race.chest':'▣ COFRE {laps}','race.viewResults':'VER RESULTADOS','race.viewReport':'VER INFORME',
    'race.survivalSessionInfo':'INFO DE SESIÓN · SUPERVIVENCIA','race.result':'resultado','race.champion':'1º / CAMPEÓN','race.eliminated':'ELIMINADO','race.rounds':'RONDAS','race.best':'MEJOR','race.average':'MEDIA','race.laps':'VUELTAS','race.worst':'PEOR','race.startingCars':'COCHES INICIALES','race.backResult':'VOLVER AL RESULTADO',
    'race.pause':'PAUSA','race.paused':'PAUSADO','race.resume':'REANUDAR','race.restart':'REINICIAR','race.exit':'SALIR','race.standings':'CLASIFICACIÓN','race.finish':'META','race.start':'SALIDA','race.newRecord':'NUEVO RÉCORD','race.record':'RÉCORD','race.practice':'PRÁCTICA','race.timeAttack':'CONTRARRELOJ','race.ghost':'FANTASMA','race.survival':'SUPERVIVENCIA','race.duel':'DUELO','race.practiceArea':'ÁREA DE PRUEBAS',
    'workshop.title':'TDR WORKSHOP','workshop.flowTop':'1 · CONSIGUE  →  2 · FUSIONA  →  3 · GUARDA  →  4 · EQUIPA','workshop.storage':'1 · ALMACÉN','workshop.storageDesc':'Todo lo que fabricas aparece aquí, en la pestaña PIEZAS.','workshop.materials':'MATERIALES','workshop.parts':'PIEZAS','workshop.new':'NUEVA','workshop.equipped':'EQUIPADA','workshop.equip':'EQUIPAR','workshop.emptyParts':'AÚN NO HAS FABRICADO PIEZAS\n\nFusiona materiales en el banco central.','workshop.bench':'2 · BANCO DE FUSIÓN','workshop.benchDesc':'Toca dos materiales del almacén.\nSi existe receta, verás el resultado antes de fabricar.','workshop.result':'RESULTADO  →  {result}','workshop.craftPart':'FABRICAR PIEZA','workshop.selectRecipe':'SELECCIONA UNA RECETA','workshop.examples':'EJEMPLOS','workshop.doubleLoot':'▶ DUPLICAR ÚLTIMO BOTÍN','workshop.loadout':'3 · COCHE / MONTAJE','workshop.loadoutDesc':'Las piezas fabricadas se equipan desde ALMACÉN → PIEZAS.','workshop.noPart':'SIN PIEZA EQUIPADA','workshop.flow':'FLUJO\nFABRICAR → se guarda en PIEZAS → pulsa EQUIPAR → aparece aquí','workshop.select':'Selecciona','workshop.doubleLootTitle':'DUPLICAR BOTÍN','workshop.lootDoubled':'Botín duplicado','workshop.alreadyClaimed':'Ya reclamado','workshop.pickTwo':'Selecciona dos materiales','workshop.crafted':'FABRICADO · {item} · guardado en {bucket}','workshop.upgrade':'EVOLUCIÓN · {item}','workshop.installed':'{item} equipada en {family}',
    'family.engine':'MOTOR','family.brakes':'FRENOS','family.tires':'RUEDAS','family.suspension':'SUSPENSIÓN','family.transmission':'CAJA',
    'induction.firstDrive.title':'Primeros metros','induction.firstDrive.desc':'Completa tu primera vuelta válida.','induction.garageVisit.title':'Conoce tu máquina','induction.garageVisit.desc':'Entra en el garaje y echa un vistazo a tu coche.','induction.materialStart.title':'Primer botín','induction.materialStart.desc':'Corre hasta conseguir tus primeros materiales.','induction.firstCraft.title':'Manos a la obra','induction.firstCraft.desc':'Fabrica tu primera pieza para el coche.','induction.equipPart.title':'Ajusta el coche','induction.equipPart.desc':'Equipa una pieza fabricada en uno de tus coches.','induction.cleanStart.title':'Conduce limpio','induction.cleanStart.desc':'Completa 2 vueltas sin salirte del circuito.','induction.storeBuy.title':'De compras','induction.storeBuy.desc':'Compra un pack de materiales usando monedas del juego.','induction.trackTour.title':'Cambia de escenario','induction.trackTour.desc':'Completa al menos una vuelta en 2 circuitos distintos.','induction.modeTour.title':'Prueba algo diferente','induction.modeTour.desc':'Inicia otro modo de juego desde el selector de modos.','induction.materialHunt.title':'Coleccionista','induction.materialHunt.desc':'Consigue 20 nuevas tiradas de materiales compitiendo.','induction.cleanRhythm.title':'Coge el ritmo','induction.cleanRhythm.desc':'Completa 5 vueltas sin abandonar la pista.','induction.distanceRun.title':'Suma kilómetros','induction.distanceRun.desc':'Completa 10 vueltas válidas.','induction.explorer.title':'Explorador','induction.explorer.desc':'Completa al menos 2 vueltas en 3 circuitos distintos.','induction.final.title':'Piloto completo','induction.final.desc':'Demuestra lo aprendido: 5 vueltas, 3 limpias y 2 circuitos.','induction.label.lap':'VUELTA','induction.label.laps':'VUELTAS','induction.label.visit':'VISITA','induction.label.lootDrops':'BOTINES','induction.label.part':'PIEZA','induction.label.equipped':'EQUIPADA','induction.label.cleanLaps':'LIMPIAS','induction.label.purchase':'COMPRA','induction.label.tracks':'CIRCUITOS','induction.label.mode':'MODO','induction.label.objectives':'OBJETIVOS','induction.label.progress':'PROGRESO','induction.reward.avenirGripline':'AVENIR Gripline',
    'store.title':'TIENDA','store.buy':'COMPRAR','store.owned':'EN PROPIEDAD','store.coins':'MONEDAS','store.notEnough':'MONEDAS INSUFICIENTES','store.close':'CERRAR'
  }),
  en:Object.freeze({
    'common.back':'BACK','common.close':'CLOSE','common.cancel':'CANCEL','common.select':'SELECT','common.selected':'SELECTED','common.edit':'EDIT','common.continue':'CONTINUE','common.results':'RESULTS','common.report':'REPORT','common.best':'BEST','common.lap':'LAP','common.laps':'LAPS','common.total':'TOTAL','common.time':'TIME','common.speed':'SPEED','common.position':'POSITION','common.penalty':'PENALTY','common.yes':'YES','common.no':'NO',
    'track.atlantic':'ATLANTIC CIRCUIT','track.generic':'Track','car.generic':'Car',
    'race.emptySession':'No completed laps in this session yet.','race.lapsSectors':'Laps · Sectors','race.bestSession':'SESSION BEST','race.sectorRecord':'SECTOR RECORD','race.bestSessionShort':'SESSION BEST','race.sectorRecordShort':'SECTOR RECORD','race.noTimedLaps':'No timed laps.',
    'race.sessionFinished':'SESSION COMPLETE','race.chestLaps':'{laps}-LAP CHEST','race.sessionLoot':'SESSION LOOT','race.sessionLootDesc':'Everything earned during the stint is delivered together.','race.level':'LEVEL {level}','race.tapOpen':'TAP TO OPEN','race.materialRewards':'8 MATERIALS · TOTAL REWARDS','race.pieces':'{count} ITEMS','race.rewardedLaps':'🏁 {laps} REWARDED LAPS','race.bonus':'⚡ {laps} BONUS','race.chest':'▣ CHEST {laps}','race.viewResults':'VIEW RESULTS','race.viewReport':'VIEW REPORT',
    'race.survivalSessionInfo':'SESSION INFO · SURVIVAL','race.result':'result','race.champion':'1ST / CHAMPION','race.eliminated':'ELIMINATED','race.rounds':'ROUNDS','race.best':'BEST','race.average':'AVERAGE','race.laps':'LAPS','race.worst':'WORST','race.startingCars':'STARTING CARS','race.backResult':'BACK TO RESULT',
    'race.pause':'PAUSE','race.paused':'PAUSED','race.resume':'RESUME','race.restart':'RESTART','race.exit':'EXIT','race.standings':'STANDINGS','race.finish':'FINISH','race.start':'START','race.newRecord':'NEW RECORD','race.record':'RECORD','race.practice':'PRACTICE','race.timeAttack':'TIME ATTACK','race.ghost':'GHOST','race.survival':'SURVIVAL','race.duel':'DUEL','race.practiceArea':'PRACTICE AREA',
    'workshop.title':'TDR WORKSHOP','workshop.flowTop':'1 · COLLECT  →  2 · COMBINE  →  3 · STORE  →  4 · EQUIP','workshop.storage':'1 · STORAGE','workshop.storageDesc':'Everything you craft appears here under PARTS.','workshop.materials':'MATERIALS','workshop.parts':'PARTS','workshop.new':'NEW','workshop.equipped':'EQUIPPED','workshop.equip':'EQUIP','workshop.emptyParts':'YOU HAVE NOT CRAFTED ANY PARTS YET\n\nCombine materials at the central bench.','workshop.bench':'2 · CRAFTING BENCH','workshop.benchDesc':'Tap two materials from storage.\nIf a recipe exists, you will see the result before crafting.','workshop.result':'RESULT  →  {result}','workshop.craftPart':'CRAFT PART','workshop.selectRecipe':'SELECT A RECIPE','workshop.examples':'EXAMPLES','workshop.doubleLoot':'▶ DOUBLE LAST LOOT','workshop.loadout':'3 · CAR / LOADOUT','workshop.loadoutDesc':'Crafted parts are equipped from STORAGE → PARTS.','workshop.noPart':'NO PART EQUIPPED','workshop.flow':'FLOW\nCRAFT → stored in PARTS → tap EQUIP → appears here','workshop.select':'Select','workshop.doubleLootTitle':'DOUBLE LOOT','workshop.lootDoubled':'Loot doubled','workshop.alreadyClaimed':'Already claimed','workshop.pickTwo':'Select two materials','workshop.crafted':'CRAFTED · {item} · stored in {bucket}','workshop.upgrade':'UPGRADE · {item}','workshop.installed':'{item} equipped in {family}',
    'family.engine':'ENGINE','family.brakes':'BRAKES','family.tires':'TIRES','family.suspension':'SUSPENSION','family.transmission':'GEARBOX',
    'induction.firstDrive.title':'First Miles','induction.firstDrive.desc':'Complete your first valid lap.','induction.garageVisit.title':'Know Your Machine','induction.garageVisit.desc':'Visit the garage and take a look at your car.','induction.materialStart.title':'First Loot','induction.materialStart.desc':'Race until you earn your first materials.','induction.firstCraft.title':'Hands On','induction.firstCraft.desc':'Craft your first car part.','induction.equipPart.title':'Tune the Car','induction.equipPart.desc':'Equip a crafted part on one of your cars.','induction.cleanStart.title':'Drive Clean','induction.cleanStart.desc':'Complete 2 laps without leaving the track.','induction.storeBuy.title':'Shop Visit','induction.storeBuy.desc':'Buy a material pack using in-game coins.','induction.trackTour.title':'Change of Scenery','induction.trackTour.desc':'Complete at least one lap on 2 different tracks.','induction.modeTour.title':'Try Something New','induction.modeTour.desc':'Start another game mode from the mode selector.','induction.materialHunt.title':'Collector','induction.materialHunt.desc':'Earn 20 new material drops by racing.','induction.cleanRhythm.title':'Find Your Rhythm','induction.cleanRhythm.desc':'Complete 5 laps without leaving the track.','induction.distanceRun.title':'Build Mileage','induction.distanceRun.desc':'Complete 10 valid laps.','induction.explorer.title':'Explorer','induction.explorer.desc':'Complete at least 2 laps on 3 different tracks.','induction.final.title':'Complete Driver','induction.final.desc':'Show what you learned: 5 laps, 3 clean laps and 2 tracks.','induction.label.lap':'LAP','induction.label.laps':'LAPS','induction.label.visit':'VISIT','induction.label.lootDrops':'LOOT DROPS','induction.label.part':'PART','induction.label.equipped':'EQUIPPED','induction.label.cleanLaps':'CLEAN LAPS','induction.label.purchase':'PURCHASE','induction.label.tracks':'TRACKS','induction.label.mode':'MODE','induction.label.objectives':'OBJECTIVES','induction.label.progress':'PROGRESS','induction.reward.avenirGripline':'AVENIR Gripline',
    'store.title':'STORE','store.buy':'BUY','store.owned':'OWNED','store.coins':'COINS','store.notEnough':'NOT ENOUGH COINS','store.close':'CLOSE'
  })
});

export function extraTranslation(language,key){
  const lang=String(language||'en').toLowerCase().startsWith('es')?'es':'en';
  return EXTRA[lang]?.[key];
}
