const LEGAL_COPY={
  ads:{title:'Privacidad de anuncios y consentimiento',body:`<p>Top Down RACE puede mostrar publicidad mediante servicios de terceros integrados en la aplicación. En las compilaciones móviles, la gestión del consentimiento publicitario se realiza mediante las herramientas de consentimiento proporcionadas por Google cuando resultan aplicables según la región, la configuración del dispositivo y los requisitos legales vigentes.</p><p>Los proveedores publicitarios pueden tratar información técnica necesaria para prestar, limitar, medir o proteger el servicio publicitario. Según la configuración disponible, esta información puede incluir identificadores del dispositivo o de publicidad, información técnica de la aplicación y del dispositivo, interacciones con anuncios y señales utilizadas para medición y prevención del fraude.</p><p>La disponibilidad de anuncios personalizados o no personalizados depende de las opciones de consentimiento, la región y la plataforma publicitaria. Modificar estas opciones no altera las funciones principales de conducción del juego, aunque puede cambiar la forma en que se sirven los anuncios o determinadas recompensas asociadas a publicidad.</p><h3>Gestión del consentimiento</h3><p>La opción “Gestionar privacidad” está destinada a volver a abrir, cuando la compilación móvil lo permita, el formulario de opciones de privacidad de Google. Este acceso sustituirá al control flotante externo para mantener las opciones de privacidad dentro de Configuración.</p>`},
  privacy:{title:'Política de privacidad',body:`<p>Esta información resume las prácticas de privacidad de Top Down RACE: CraftRace. La política pública vigente asociada a la aplicación es la referencia principal y debe mantenerse accesible desde Google Play y desde la propia aplicación.</p><p>El juego puede utilizar servicios de terceros necesarios para publicidad, compras dentro de la aplicación, validación de productos digitales, diagnóstico técnico y servicios propios de la plataforma. Esos servicios pueden tratar datos técnicos del dispositivo, identificadores, información de transacciones, datos de consentimiento y eventos de funcionamiento necesarios para prestar sus respectivas funciones. El tratamiento concreto depende de la plataforma, la versión instalada y las funciones utilizadas.</p><p>CraftRace Studio utiliza la información relacionada con el funcionamiento del juego para las finalidades declaradas y necesarias para prestar el servicio. Cuando interviene un proveedor externo, sus propias condiciones y políticas también pueden resultar aplicables.</p><h3>Conservación y seguridad</h3><p>Determinados ajustes, progreso y registros pueden almacenarse localmente en el dispositivo. Los datos tratados por proveedores externos están sujetos a sus propios periodos de conservación y a las obligaciones legales aplicables. Las comunicaciones con servicios remotos se realizan mediante mecanismos de conexión segura cuando corresponde.</p><h3>Consultas</h3><p>Las consultas relacionadas con privacidad pueden realizarse mediante los canales oficiales de soporte publicados para Top Down RACE. Cuando una solicitud afecte a información controlada directamente por una plataforma o proveedor externo, puede ser necesario utilizar también las herramientas que dicho proveedor ofrece al usuario.</p>`},
  support:{title:'Soporte y contacto',body:`<p>El soporte de Top Down RACE se presta mediante los canales oficiales publicados por CraftRace Studio en la ficha de la aplicación y en el sitio web oficial del juego. Pueden utilizarse para comunicar errores, problemas de acceso, incidencias con compras, dudas sobre privacidad o dificultades técnicas.</p><p>Para investigar una incidencia puede solicitarse información técnica razonablemente necesaria, como versión de la aplicación, plataforma, modelo de dispositivo, versión del sistema operativo, descripción del problema y pasos para reproducirlo. El usuario no debe facilitar información sensible que no sea necesaria para resolver la consulta.</p><p>Las compras y reembolsos pueden estar sujetos además a los procedimientos de Google Play, Apple App Store u otros distribuidores autorizados. CraftRace Studio no controla los datos de pago gestionados directamente por esas plataformas.</p><h3>Disponibilidad</h3><p>El envío de una consulta no garantiza un plazo concreto de resolución. Las incidencias se revisan atendiendo a su impacto, reproducibilidad y relación con las versiones actualmente distribuidas del juego.</p>`},
  legal:{title:'Información legal y condiciones de uso',body:`<p>Top Down RACE: CraftRace es un videojuego distribuido bajo la identidad de desarrollador CraftRace Studio. El juego contiene software, gráficos, interfaces, sonidos, textos, marcas y otros elementos protegidos por la normativa aplicable y por los derechos de sus respectivos titulares.</p><p>El usuario recibe un derecho limitado de uso personal conforme a las condiciones de la plataforma desde la que haya obtenido el juego. Este derecho no implica una cesión de propiedad intelectual ni autoriza la extracción, redistribución o explotación independiente de los recursos del juego fuera de los usos permitidos legalmente.</p><h3>Servicios y contenido digital</h3><p>El juego puede incluir publicidad, recompensas, monedas virtuales, elementos desbloqueables y compras dentro de la aplicación. Los objetos o monedas virtuales forman parte del servicio digital del juego y no constituyen dinero de curso legal. Las compras se procesan mediante la plataforma de distribución correspondiente y están sujetas a sus condiciones.</p><h3>Actualizaciones</h3><p>Las características, equilibrio, disponibilidad de contenidos, compatibilidad técnica y servicios conectados pueden cambiar mediante actualizaciones destinadas a corregir errores, mejorar el juego, mantener compatibilidad o cumplir requisitos técnicos y legales. Las versiones de prueba pueden contener funciones experimentales o incidencias todavía en proceso de corrección.</p><h3>Uso adecuado</h3><p>El usuario debe utilizar el juego de forma lícita y no interferir deliberadamente con su funcionamiento, sistemas de clasificación, servicios, medidas de seguridad o mecanismos de monetización.</p>`}
};

function ensureStyle(){
  if(document.getElementById('tdr-settings-legal-enhancer'))return;
  const s=document.createElement('style');s.id='tdr-settings-legal-enhancer';s.textContent=`
    #tdr-settings2 .s2tabs{display:flex!important;gap:7px!important;width:100%!important;min-width:0!important}
    #tdr-settings2 .s2tab{flex:1 1 0!important;min-width:0!important;padding:9px 6px!important;font-size:clamp(8px,.95vw,11px)!important;letter-spacing:.015em!important;white-space:nowrap!important}
    #tdr-settings2 .s2body .s2card[data-legal-kind]{cursor:pointer}
    #tdr-settings2 .s2body .s2card[data-legal-kind]:active{border-color:rgba(112,255,173,.5)!important}
    .tdr-legal-modal{position:fixed;inset:0;z-index:30000;background:rgba(0,0,0,.78);display:flex;align-items:center;justify-content:center;padding:5vh 6vw;font-family:Arial,Helvetica,sans-serif;color:#bfc3c8;user-select:text;-webkit-user-select:text}
    .tdr-legal-paper{width:min(900px,88vw);max-height:78vh;overflow:auto;background:#12151a;border:1px solid #363b43;border-radius:6px;padding:24px 28px;box-shadow:0 20px 70px #000;font-size:11px;line-height:1.65}
    .tdr-legal-paper h2{margin:0 0 16px;color:#e0e0e0;font-size:15px}.tdr-legal-paper h3{margin:18px 0 6px;color:#d0d0d0;font-size:11px}.tdr-legal-paper p{margin:0 0 10px}.tdr-legal-close{margin-top:18px;padding-top:9px;border-top:1px solid #2b3037;text-align:center;color:#707780;font-size:9px}
    @media(max-width:760px){#tdr-settings2 .s2tabs{gap:4px!important}#tdr-settings2 .s2tab{padding:7px 3px!important;font-size:7.5px!important;letter-spacing:0!important}.tdr-legal-paper{width:92vw;max-height:82vh;padding:18px;font-size:10px}}
  `;document.head.appendChild(s);
}

function openLegal(kind){
  document.querySelector('.tdr-legal-modal')?.remove();
  const d=LEGAL_COPY[kind]||LEGAL_COPY.legal,m=document.createElement('div');m.className='tdr-legal-modal';
  m.innerHTML=`<article class="tdr-legal-paper"><h2>${d.title}</h2>${d.body}<div class="tdr-legal-close">Toca en cualquier lugar para cerrar</div></article>`;
  m.addEventListener('click',()=>m.remove());document.body.appendChild(m);
}

function wireLegal(){
  const root=document.getElementById('tdr-settings2');if(!root)return;
  const labels=[...root.querySelectorAll('.s2label')];
  const map=[['PRIVACIDAD DE ANUNCIOS','ads'],['POLÍTICA DE PRIVACIDAD','privacy'],['SOPORTE','support'],['INFORMACIÓN LEGAL','legal']];
  for(const [label,kind] of map){
    const el=labels.find(x=>x.textContent.trim()===label),card=el?.closest('.s2card');if(!card||card.dataset.legalKind)return;
    card.dataset.legalKind=kind;card.setAttribute('role','button');card.tabIndex=0;
    const go=e=>{if(e.target?.closest?.('.s2cta'))return;openLegal(kind)};
    card.addEventListener('click',go);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openLegal(kind)}});
  }
}

ensureStyle();wireLegal();
new MutationObserver(()=>wireLegal()).observe(document.documentElement,{subtree:true,childList:true});
