import { shipatonJudgeModeEnabled, setShipatonJudgeMode, syncJudgeBadge } from '../game/shipaton/ShipatonJudgeMode.js';

const LEGAL_COPY={
  ads:{title:'Privacidad de anuncios y consentimiento',body:`<p>Top Down RACE puede mostrar publicidad mediante servicios de terceros integrados en la aplicación. En las compilaciones móviles, la gestión del consentimiento publicitario se realiza mediante las herramientas de consentimiento proporcionadas por Google cuando resultan aplicables según la región, la configuración del dispositivo y los requisitos legales vigentes.</p><p>Los proveedores publicitarios pueden tratar información técnica necesaria para prestar, limitar, medir o proteger el servicio publicitario. Según la configuración disponible, esta información puede incluir identificadores del dispositivo o de publicidad, información técnica de la aplicación y del dispositivo, interacciones con anuncios y señales utilizadas para medición y prevención del fraude.</p>`},
  privacy:{title:'Política de privacidad',body:`<p>Esta información resume las prácticas de privacidad de Top Down RACE: CraftRace. La política pública vigente asociada a la aplicación es la referencia principal y debe mantenerse accesible desde Google Play y desde la propia aplicación.</p>`},
  support:{title:'Soporte y contacto',body:`<p>El soporte de Top Down RACE se presta mediante los canales oficiales publicados por CraftRace Studio en la ficha de la aplicación y en el sitio web oficial del juego.</p>`},
  legal:{title:'Información legal y condiciones de uso',body:`<p>Top Down RACE: CraftRace es un videojuego distribuido bajo la identidad de desarrollador CraftRace Studio.</p><p>El juego puede incluir publicidad, recompensas, monedas virtuales, elementos desbloqueables y compras dentro de la aplicación.</p>`}
};
function ensureStyle(){if(document.getElementById('tdr-settings-legal-enhancer'))return;const s=document.createElement('style');s.id='tdr-settings-legal-enhancer';s.textContent=`#tdr-settings2 .s2tabs{display:flex!important;gap:7px!important;width:100%!important;min-width:0!important}#tdr-settings2 .s2tab{flex:1 1 0!important;min-width:0!important;padding:9px 6px!important;font-size:clamp(8px,.95vw,11px)!important;letter-spacing:.015em!important;white-space:nowrap!important}.tdr-legal-modal,.tdr-judge-modal{position:fixed;inset:0;z-index:30000;background:rgba(0,0,0,.78);display:flex;align-items:center;justify-content:center;padding:5vh 6vw;font-family:Arial,Helvetica,sans-serif;color:#bfc3c8}.tdr-legal-paper,.tdr-judge-paper{width:min(900px,88vw);max-height:78vh;overflow:auto;background:#12151a;border:1px solid #363b43;border-radius:8px;padding:24px 28px;box-shadow:0 20px 70px #000;font-size:11px;line-height:1.65}.tdr-legal-paper h2,.tdr-judge-paper h2{margin:0 0 12px;color:#e0e0e0;font-size:16px}.tdr-judge-state{margin:14px 0;padding:12px;border:1px solid #344b5d;border-radius:8px;background:#08131d}.tdr-judge-state.on{border-color:#58e8ff;color:#9bf2ff}.tdr-judge-actions{display:flex;gap:10px;margin-top:16px}.tdr-judge-actions button{flex:1;padding:11px;border-radius:8px;font-weight:900}.tdr-judge-toggle{border:1px solid #58e8ff;background:#103745;color:#9bf2ff}.tdr-judge-close{border:1px solid #4b5662;background:#171d24;color:#d6dce2}.tdr-judge-guide{margin-top:14px;padding-top:12px;border-top:1px solid #303841}.tdr-judge-guide strong{color:#fff}@media(max-width:760px){#tdr-settings2 .s2tabs{gap:4px!important}#tdr-settings2 .s2tab{padding:7px 3px!important;font-size:7.2px!important;letter-spacing:0!important}.tdr-legal-paper,.tdr-judge-paper{width:92vw;max-height:82vh;padding:18px;font-size:10px}}`;document.head.appendChild(s)}
function openLegal(kind){document.querySelector('.tdr-legal-modal')?.remove();const d=LEGAL_COPY[kind]||LEGAL_COPY.legal,m=document.createElement('div');m.className='tdr-legal-modal';m.innerHTML=`<article class="tdr-legal-paper"><h2>${d.title}</h2>${d.body}<div style="margin-top:18px;text-align:center;color:#707780">Toca para cerrar</div></article>`;m.addEventListener('click',()=>m.remove());document.body.appendChild(m)}
function openJudge(){document.querySelector('.tdr-judge-modal')?.remove();const active=shipatonJudgeModeEnabled(),m=document.createElement('div');m.className='tdr-judge-modal';m.innerHTML=`<article class="tdr-judge-paper"><h2>SHIPATON 2026 · MODO JUECES</h2><p>Acceso de evaluación: permite ver y probar el contenido disponible para evaluación sin convertir ese acceso en progreso normal de la partida.</p><div class="tdr-judge-state ${active?'on':''}">${active?'● MODO JUECES ACTIVO':'○ MODO JUECES DESACTIVADO'}</div><div class="tdr-judge-guide"><strong>GUÍA DEL JURADO</strong><p>• Garaje: inspecciona y prueba la flota completa disponible.<br>• Circuitos: accede al contenido de circuito disponible para evaluación.<br>• Monetización: prueba Recicladora, vídeo recompensado de Tienda y x2 de botín postcarrera.<br>• Progresión: este modo no debe conceder desbloqueos, monedas ni materiales únicamente por activarlo.</p></div><div class="tdr-judge-actions"><button class="tdr-judge-close">CERRAR</button><button class="tdr-judge-toggle">${active?'DESACTIVAR':'ACTIVAR'} MODO JUECES</button></div></article>`;document.body.appendChild(m);m.querySelector('.tdr-judge-close').onclick=()=>m.remove();m.querySelector('.tdr-judge-toggle').onclick=()=>{setShipatonJudgeMode(!active);m.remove();openJudge()}}
function wireLegal(){const root=document.getElementById('tdr-settings2');if(!root)return;const tabs=root.querySelector('.s2tabs');if(tabs&&!tabs.querySelector('[data-shipaton]')){const b=document.createElement('button');b.className='s2tab';b.dataset.shipaton='1';b.textContent='SHIPATON 2026';b.onclick=e=>{e.preventDefault();openJudge()};tabs.appendChild(b)}const labels=[...root.querySelectorAll('.s2label')],map=[['PRIVACIDAD DE ANUNCIOS','ads'],['POLÍTICA DE PRIVACIDAD','privacy'],['SOPORTE','support'],['INFORMACIÓN LEGAL','legal']];for(const [label,kind] of map){const el=labels.find(x=>x.textContent.trim()===label),card=el?.closest('.s2card');if(!card||card.dataset.legalKind)continue;card.dataset.legalKind=kind;card.setAttribute('role','button');card.tabIndex=0;const go=e=>{if(e.target?.closest?.('.s2cta'))return;openLegal(kind)};card.addEventListener('click',go);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openLegal(kind)}})}}
ensureStyle();wireLegal();syncJudgeBadge();new MutationObserver(()=>wireLegal()).observe(document.documentElement,{subtree:true,childList:true});
