import { MenuScene as PreviousMenuScene } from './MenuCoinAssetScene.js';
import { MATERIAL_PACKS,COIN_PACKS,buyMaterialPack,simulateCoinPurchase,rewardedStatus,claimRewardedCoins,dailyStatus,claimDailyCoins } from '../store/storeEconomy.js';
import { loadGarage } from '../garage/garageStore.js';
import { GARAGE_ITEMS } from '../garage/partsCatalog.js';
import { preloadTdrCoin, replaceProceduralCoins } from '../ui/CoinAssetUi.js';

const FONT='system-ui,-apple-system,Segoe UI,Arial';
const fmt=n=>Math.max(0,Math.floor(Number(n)||0)).toLocaleString('es-ES');
const timeLabel=ms=>{const s=Math.ceil(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),ss=s%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}`;};

export class MenuScene extends PreviousMenuScene{
 preload(){super.preload?.();preloadTdrCoin(this);for(const id of ['scrap','alloy','rubber','compound','disc','spring','gear','ecu']){const it=GARAGE_ITEMS[id];if(it?.asset&&!this.textures.exists(`store:${id}`))this.load.image(`store:${id}`,it.asset);}}
 _renderTopLobbyHeader(){super._renderTopLobbyHeader?.();const root=this._topLobbyHeader;if(!root)return;const w=this.scale.width;const bg=this.add.rectangle(w-470,6,118,36,0x542f91,.96).setOrigin(0).setStrokeStyle(2,0xc987ff,.8).setInteractive({useHandCursor:true});const tx=this.add.text(w-411,24,'TIENDA',{fontFamily:FONT,fontSize:'11px',fontStyle:'bold',color:'#fff',letterSpacing:1}).setOrigin(.5);root.add([bg,tx]);bg.on('pointerup',()=>this._openStoreModal('materials'));}
 _openStoreModal(section='materials'){
  try{this._storeModal?.destroy?.(true);}catch{};const {width:w,height:h}=this.scale;const root=this.add.container(0,0).setDepth(25000);this._ui?.add(root);this._storeModal=root;
  root.add(this.add.rectangle(0,0,w,h,0x06101b,.99).setOrigin(0).setInteractive());
  const top=this.add.rectangle(0,0,w,58,0x101c3a,1).setOrigin(0);root.add(top);root.add(this.add.text(26,27,'TIENDA',{fontFamily:FONT,fontSize:'28px',fontStyle:'bold',color:'#fff',stroke:'#07101d',strokeThickness:5}).setOrigin(0,.5));
  const coins=loadGarage().coins||0;root.add(this.add.text(w-142,29,`◈ ${fmt(coins)}`,{fontFamily:FONT,fontSize:'17px',fontStyle:'bold',color:'#ffd85a'}).setOrigin(.5));
  const close=this.add.text(w-30,29,'✕',{fontFamily:FONT,fontSize:'25px',fontStyle:'bold',color:'#fff'}).setOrigin(.5).setInteractive({useHandCursor:true});root.add(close);close.on('pointerup',()=>{root.destroy(true);this._storeModal=null;});
  const navY=72,nav=[['materials','MATERIALES'],['coins','MONEDAS'],['rewards','RECOMPENSAS']];let nx=24;for(const [id,label] of nav){const active=id===section,b=this.add.rectangle(nx,navY,150,34,active?0x28a9e8:0x17253b,1).setOrigin(0).setStrokeStyle(2,active?0x7be5ff:0x344c68,1).setInteractive({useHandCursor:true});const t=this.add.text(nx+75,navY+17,label,{fontFamily:FONT,fontSize:'10px',fontStyle:'bold',color:'#fff'}).setOrigin(.5);root.add([b,t]);b.on('pointerup',()=>this._openStoreModal(id));nx+=158;}
  const viewportX=22,viewportY=120,viewportW=w-44,viewportH=h-140;const clip=this.add.graphics().fillStyle(0xffffff).fillRect(viewportX,viewportY,viewportW,viewportH);clip.setVisible(false);root.add(clip);const content=this.add.container(viewportX,viewportY);content.setMask(clip.createGeometryMask());root.add(content);
  const cards=[];if(section==='materials')MATERIAL_PACKS.forEach((p,i)=>cards.push({type:'mat',...p,accent:[0x28a9e8,0x48cf8b,0xe4a83b,0xa76ce5][i%4]}));if(section==='coins')COIN_PACKS.forEach((p,i)=>cards.push({type:'coin',...p,accent:[0x37b8ff,0x6bd35e,0xe4a83b,0xb26bea][i%4]}));if(section==='rewards'){cards.push({type:'reward',id:'video',name:'VÍDEO RECOMPENSADO',accent:0xe4a83b});cards.push({type:'daily',id:'daily',name:'REGALO DIARIO',accent:0x48cf8b});}
  const cardW=Math.min(330,w*.31),cardH=viewportH-14,gap=16;cards.forEach((p,i)=>this._storeCard(content,p,i*(cardW+gap),0,cardW,cardH,section));const total=Math.max(viewportW,cards.length*(cardW+gap)-gap);let dragStart=null,startX=0;const hit=this.add.rectangle(viewportX,viewportY,viewportW,viewportH,0xffffff,0.001).setOrigin(0).setInteractive({draggable:true});root.add(hit);hit.on('dragstart',ptr=>{dragStart=ptr.x;startX=content.x;});hit.on('drag',(ptr)=>{if(dragStart===null)return;content.x=Math.max(viewportX-(total-viewportW),Math.min(viewportX,startX+(ptr.x-dragStart)));});hit.on('wheel',(_p,_dx,dy)=>{content.x=Math.max(viewportX-(total-viewportW),Math.min(viewportX,content.x-dy*.7));});replaceProceduralCoins(this,root,24);
 }
 _storeCard(parent,p,x,y,w,h){
  const card=this.add.container(x,y);parent.add(card);card.add(this.add.rectangle(0,0,w,h,0x132239,1).setOrigin(0).setStrokeStyle(4,p.accent,1));card.add(this.add.rectangle(7,7,w-14,h-14,p.accent,.16).setOrigin(0));
  card.add(this.add.text(18,16,p.name,{fontFamily:FONT,fontSize:'18px',fontStyle:'bold',color:'#fff',stroke:'#07101d',strokeThickness:4,wordWrap:{width:w-36}}).setOrigin(0));
  if(p.type==='mat'){const ids=Object.keys(p.items);ids.slice(0,4).forEach((id,j)=>{const key=`store:${id}`,cx=w*(.25+(j%2)*.5),cy=88+Math.floor(j/2)*82;if(this.textures.exists(key)){const im=this.add.image(cx,cy,key);im.setScale(Math.min(108/(im.width||1),70/(im.height||1)));card.add(im);}card.add(this.add.text(cx,cy+39,`${String(GARAGE_ITEMS[id]?.name||id).toUpperCase()} ×${p.items[id]}`,{fontFamily:FONT,fontSize:'9px',fontStyle:'bold',color:'#fff'}).setOrigin(.5));});this._buyButton(card,w,h,`${fmt(p.price)} MONEDAS`,()=>{const r=buyMaterialPack(p.id);this._toastStore(r.ok?'PACK AÑADIDO':r.reason,r.ok);if(r.ok)this._openStoreModal('materials');});}
  if(p.type==='coin'){card.add(this.add.text(w/2,h*.43,'◈',{fontFamily:FONT,fontSize:'92px',fontStyle:'bold',color:'#ffd34f',stroke:'#7d4d00',strokeThickness:8}).setOrigin(.5));card.add(this.add.text(w/2,h*.66,fmt(p.coins),{fontFamily:FONT,fontSize:'29px',fontStyle:'bold',color:'#fff'}).setOrigin(.5));this._buyButton(card,w,h,'COMPRA SIMULADA',()=>{simulateCoinPurchase(p.id);this._toastStore('COMPRA DE DESARROLLO',true);this._openStoreModal('coins');});}
  if(p.type==='reward'){const st=rewardedStatus();card.add(this.add.text(w/2,h*.39,'▶',{fontFamily:FONT,fontSize:'88px',fontStyle:'bold',color:'#ffd34f'}).setOrigin(.5));card.add(this.add.text(w/2,h*.62,'+250 MONEDAS',{fontFamily:FONT,fontSize:'24px',fontStyle:'bold',color:'#fff'}).setOrigin(.5));this._buyButton(card,w,h,st.available?'VER VÍDEO':`DISPONIBLE EN ${timeLabel(st.remaining)}`,()=>{if(!st.available)return;claimRewardedCoins(250);this._toastStore('+250 MONEDAS',true);this._openStoreModal('rewards');},st.available);}
  if(p.type==='daily'){const st=dailyStatus();card.add(this.add.text(w/2,h*.4,'★',{fontFamily:FONT,fontSize:'96px',fontStyle:'bold',color:'#72ffad'}).setOrigin(.5));card.add(this.add.text(w/2,h*.62,'+100 MONEDAS',{fontFamily:FONT,fontSize:'24px',fontStyle:'bold',color:'#fff'}).setOrigin(.5));this._buyButton(card,w,h,st.available?'RECLAMAR GRATIS':'VUELVE MAÑANA',()=>{if(!st.available)return;claimDailyCoins(100);this._toastStore('+100 MONEDAS',true);this._openStoreModal('rewards');},st.available);}
 }
 _buyButton(card,w,h,label,fn,enabled=true){const b=this.add.rectangle(12,h-57,w-24,43,enabled?0x2caf59:0x3a4554,1).setOrigin(0).setStrokeStyle(2,enabled?0x82ff9f:0x647080,1);if(enabled)b.setInteractive({useHandCursor:true}).on('pointerup',fn);card.add([b,this.add.text(w/2,h-35,label,{fontFamily:FONT,fontSize:'11px',fontStyle:'bold',color:'#fff',align:'center'}).setOrigin(.5)]);}
 _toastStore(msg,ok){const t=this.add.text(this.scale.width/2,105,msg,{fontFamily:FONT,fontSize:'14px',fontStyle:'bold',color:ok?'#72ffad':'#ff7373',backgroundColor:'#07101ddd',padding:{x:14,y:8}}).setOrigin(.5).setDepth(30000);this.time.delayedCall(1200,()=>t.destroy());}
}
