import { RaceScene as CurrentRaceScene } from './RaceAuthoredEnvironmentScene.js';

// DEV 1.0.111
// Karting Canarias previously replaced finishLine (and track meta finish data)
// only while the car was near a separately generated paddock gate. CP1/CP2 had
// already been generated by RaceScene from the authored canonical finish, so a
// lap could start with one finish definition and end with another. That made lap
// validity depend on circuit and game mode.
//
// Keep this wrapper in the inheritance chain for compatibility, but timing now
// follows the same contract as every other circuit: one authored finish gate,
// one checkpoint sequence and one RaceScene lap pipeline.
export class RaceScene extends CurrentRaceScene{}