import { StatsScene as ReplayStatsScene } from './StatsBroadcastReplayScene.js';
import { TRACK_REGISTRY } from '../tracks/trackRegistry.js';
import { buildTrackRibbon } from '../tracks/TrackBuilder.js';
import { CAR_SPECS } from '../cars/carSpecs.js';
import track01Environment from '../tracks/library/track01/track01.environment.json';
import santaCruzEnvironment from '../tracks/library/santa-cruz/santa-cruz.environment.json';
import kartingTenerifeEnvironment from '../tracks/library/karting-tenerife/karting-tenerife.environment.json';
import kartingCanariasEnvironment from '../tracks/library/karting-canarias/karting-canarias.environment.json';

const BASE=import.meta.env.BASE_URL||'/';
const ENVIRONMENTS={track01:track01Environment,'santa-cruz':santaCruzEnvironment,'karting-tenerife':kartingTenerifeEnvironment,'karting-canarias':kartingCanariasEnvironment};
const fmt=ms=>{ms=Math.max(0,Number(ms)||0);const m=Math.floor(ms/60000),s=(ms%60000)/1000;return`${m}:${s.toFixed(3).padStart(6,'0')}`;};
const imgCache=new Map();
function loadImage(src){if(!src)return Promise.resolve(null);if(imgCache.has(src))return imgCache.get(src);const p=new Promise(resolve=>{const im=new Image();im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=src;});imgCache.set(src,p);return p;}
function pointAt(samples,t){let i=1;while(i<samples.length&&Number(samples[i].t)<t)i++;const a=samples[Math.max(0,i-1)]||samples[0],b=samples[Math.min(samples.length-1,i)]||a;const span=Math.max(1,Number(b.t)-Number(a.t)),q=Math.max(0,Math.min(1,(t-Number(a.t))/span));let dr=Number(b.r)-Number(a.r);while(dr>Math.PI)dr-=Math.PI*2;while(dr<-Math.PI)dr+=Math.PI*2;return{x:Number(a.x)+(Number(b.x)-Number(a.x))*q,y:Number(a.y)+(Number(b.y)-Number(a.y))*q,r:Number(a.r)+dr*q};}
function worldToScreen(x,y,cam,scale,w,h){return{x:(x-cam.x)*scale+w/2,y:(y-cam.y)*scale+h/2};}
function path(ctx,points,cam,scale,w,h){ctx.beginPath();points.forEach((p,i)=>{const q=worldToScreen(Array.isArray(p)?p[0]:p.x,Array.isArray(p)?p[1]:p.y,cam,scale,w,h);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});}
function drawRibbon(ctx,ribbon,cam,scale,w,h){const left=ribbon?.left||[],right=ribbon?.right||[];if(left.length<2||right.length<2)return;ctx.beginPath();left.forEach((p,i)=>{const q=worldToScreen(p[0],p[1],cam,scale,w,h);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});for(let i=right.length-1;i>=0;i--){const q=worldToScreen(right[i][0],right[i][1],cam,scale,w,h);ctx.lineTo(q.x,q.y);}ctx.closePath();ctx.fillStyle='#575b5d';ctx.fill();for(const edge of [left,right]){path(ctx,edge,cam,scale,w,h);ctx.strokeStyle='#f4f1e8';ctx.lineWidth=Math.max(2,3.2*scale);ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();}}
function drawKerbs(ctx,ribbon,cam,scale,w,h){for(const edge of [ribbon?.left||[],ribbon?.right||[]]){for(let i=0;i<edge.length-1;i+=5){const a=edge[i],b=edge[Math.min(edge.length-1,i+4)],qa=worldToScreen(a[0],a[1],cam,scale,w,h),qb=worldToScreen(b[0],b[1],cam,scale,w,h);ctx.beginPath();ctx.moveTo(qa.x,qa.y);ctx.lineTo(qb.x,qb.y);ctx.strokeStyle=((i/5)&1)?'#f3efe8':'#c94a45';ctx.lineWidth=Math.max(3,7*scale);ctx.lineCap='butt';ctx.stroke();}}}
function drawFinish(ctx,finish,cam,scale,w,h){if(!finish?.a||!finish?.b)return;const a=worldToScreen(finish.a.x,finish.a.y,cam,scale,w,h),b=worldToScreen(finish.b.x,finish.b.y,cam,scale,w,h);const dx=b.x-a.x,dy=b.y-a.y,steps=10;for(let i=0;i<steps;i++){const t0=i/steps,t1=(i+1)/steps;ctx.beginPath();ctx.moveTo(a.x+dx*t0,a.y+dy*t0);ctx.lineTo(a.x+dx*t1,a.y+dy*t1);ctx.strokeStyle=i%2?'#101316':'#f6f6f3';ctx.lineWidth=Math.max(5,10*scale);ctx.stroke();}}
function replayWorldCache(trackId){try{return window.__tdrReplayWorldCache?.[trackId]||null;}catch{return null;}}

export class StatsScene extends ReplayStatsScene{
  _installBroadcastStyles(){super._installBroadcastStyles();if(this._root?.querySelector('[data-real-replay-style]'))return;const s=document.createElement('style');s.dataset.realReplayStyle='1';s.textContent=`.br-real-screen{position:relative;height:330px;overflow:hidden;background:#111}.br-real-screen canvas{display:block;width:100%;height:100%;background:#111}.br-real-screen:after{content:"";position:absolute;inset:0;pointer-events:none;box-shadow:inset 0 0 34px rgba(0,0,0,.26)}.br-camera-tag{position:absolute;left:10px;bottom:9px;background:rgba(2,10,16,.78);border:1px solid rgba(85,239,255,.25);padding:4px 7px;color:#8cefff;font-size:6px;font-weight:1000;letter-spacing:.12em}.br-monitor-real{min-height:406px}.br-monitor-real .br-monitor-head{height:48px}.br-monitor-real .br-controls{height:42px}@media(max-height:520px){.br-real-screen{height:270px}.br-monitor-real{min-height:346px}}`;this._root.appendChild(s);}
  async _showRaceControlReplay(record,ghost){
    this._stopRaceControlReplay();const main=this._root?.querySelector('.br-main');if(!main||!ghost?.samples?.length)return;
    const trackId=String(ghost.trackKey||record?.trackId||'track01');const track=TRACK_REGISTRY?.[trackId];if(!track)return super._showRaceControlReplay(record,ghost);
    const spec=CAR_SPECS?.[ghost.carId]||{};const carSrc=spec?.skin?`${BASE}assets/skins/${spec.skin}`:null;const carImg=await loadImage(carSrc);if(!this._root?.isConnected)return;
    const cached=replayWorldCache(trackId);
    const centerline=track.centerline||track?.meta?.centerline||[];const roadWidth=Number(track.trackWidth||track?.meta?.trackWidth)||80;const ribbon=buildTrackRibbon({centerline,trackWidth:roadWidth,grassMargin:Number(track.grassMargin)||0,sampleStepPx:Number(track.sampleStepPx)||10});
    const env=ENVIRONMENTS[trackId]||null;const envItems=(env?.environment||[]).filter(item=>item?.path);let envMap=new Map();if(!cached){const unique=[...new Set(envItems.map(item=>`${BASE}assets/${item.path}`))];const imgs=await Promise.all(unique.map(loadImage));envMap=new Map(unique.map((src,i)=>[src,imgs[i]]));}
    this._brAnalysisMarkup=main.innerHTML;main.innerHTML=`<section class="br-panel br-monitor br-monitor-real"><div class="br-monitor-head"><div><div class="br-label">RACE CONTROL // REPLAY</div><strong>${String(track.name||trackId).toUpperCase()}</strong><small>${String(spec.name||ghost.carId||'COCHE').toUpperCase()} · ${fmt(ghost.lapMs)}</small></div><span class="br-monitor-live">● REPLAY</span></div><div class="br-real-screen"><canvas data-br-real-canvas width="900" height="420"></canvas><div class="br-replay-hud"><div><small>TIEMPO</small><strong data-br-replay-time>0:00.000</strong></div><div><small>VUELTA</small><strong>${fmt(ghost.lapMs)}</strong></div></div><div class="br-camera-tag">${cached?'TV CAM · PHASER WORLD':'TV CAM · FALLBACK'}</div></div><div class="br-controls"><button data-br-toggle>Ⅱ</button><div class="br-seek"><i></i></div><button class="br-analysis-back" data-br-analysis>ANÁLISIS</button></div></section>`;
    const canvas=main.querySelector('[data-br-real-canvas]'),ctx=canvas?.getContext('2d');if(!ctx)return;const timeEl=main.querySelector('[data-br-replay-time]'),bar=main.querySelector('.br-seek i'),toggle=main.querySelector('[data-br-toggle]');
    let playing=true,start=performance.now(),elapsed=0;const duration=Number(ghost.lapMs)||Number(ghost.samples.at(-1)?.t)||1;let cam={x:Number(ghost.samples[0]?.x)||0,y:Number(ghost.samples[0]?.y)||0};
    const gameplayScale=Math.max(.78,Math.min(1.08,88/Math.max(70,roadWidth)));
    const render=t=>{const car=pointAt(ghost.samples,t),w=canvas.width,h=canvas.height;cam.x+=(car.x-cam.x)*.14;cam.y+=(car.y-cam.y)*.14;ctx.clearRect(0,0,w,h);
      if(cached?.canvas){const cScale=Number(cached.scale)||1;const displayScale=gameplayScale/cScale;const sw=w/displayScale,sh=h/displayScale;let sx=cam.x*cScale-sw/2,sy=cam.y*cScale-sh/2;sx=Math.max(0,Math.min(cached.width-sw,sx));sy=Math.max(0,Math.min(cached.height-sh,sy));ctx.drawImage(cached.canvas,sx,sy,sw,sh,0,0,w,h);}else{ctx.fillStyle='#183d24';ctx.fillRect(0,0,w,h);drawRibbon(ctx,ribbon,cam,gameplayScale,w,h);drawKerbs(ctx,ribbon,cam,gameplayScale,w,h);drawFinish(ctx,track.finishLine||track.finish,cam,gameplayScale,w,h);for(const item of envItems){const im=envMap.get(`${BASE}assets/${item.path}`);if(!im)continue;const q=worldToScreen(Number(item.x),Number(item.y),cam,gameplayScale,w,h),targetW=(Number(item.displayWidth)||im.naturalWidth||40)*gameplayScale;if(q.x<-220||q.x>w+220||q.y<-220||q.y>h+220)continue;const ratio=(im.naturalHeight||1)/(im.naturalWidth||1),targetH=targetW*ratio;ctx.save();ctx.translate(q.x,q.y);ctx.rotate(Number(item.rotation)||0);ctx.scale(item.flipX?-1:1,item.flipY?-1:1);ctx.drawImage(im,-targetW/2,-targetH/2,targetW,targetH);ctx.restore();}}
      const cp=worldToScreen(car.x,car.y,cam,gameplayScale,w,h);if(carImg){const vm=cached?.carVisual||{};const worldW=Number(vm.width)>0?Number(vm.width):roadWidth*.29;const worldH=Number(vm.height)>0?Number(vm.height):worldW*((carImg.naturalHeight||1)/(carImg.naturalWidth||1));ctx.save();ctx.translate(cp.x,cp.y);ctx.rotate(car.r+Math.PI/2+(Number(vm.rotation)||0));ctx.shadowColor='rgba(0,0,0,.42)';ctx.shadowBlur=5;ctx.drawImage(carImg,-worldW*gameplayScale/2,-worldH*gameplayScale/2,worldW*gameplayScale,worldH*gameplayScale);ctx.restore();}}
    const frame=now=>{if(!this._brReplayState)return;if(playing)elapsed=Math.min(duration,elapsed+(now-start));start=now;render(elapsed);if(timeEl)timeEl.textContent=fmt(elapsed);if(bar)bar.style.width=`${Math.min(100,elapsed/duration*100)}%`;if(elapsed>=duration){playing=false;if(toggle)toggle.textContent='↻';}this._brReplayState.raf=requestAnimationFrame(frame);};render(0);this._brReplayState={raf:requestAnimationFrame(frame)};
    toggle?.addEventListener('click',()=>{if(elapsed>=duration){elapsed=0;playing=true;toggle.textContent='Ⅱ';cam={x:Number(ghost.samples[0]?.x)||0,y:Number(ghost.samples[0]?.y)||0};start=performance.now();return;}playing=!playing;toggle.textContent=playing?'Ⅱ':'▶';start=performance.now();});main.querySelector('[data-br-analysis]')?.addEventListener('click',()=>this._restoreRaceControlAnalysis(main));
  }
}
