import { StatsScene as CompactStatsScene } from './StatsBroadcastCompactScene.js';

const readGhost=key=>{try{const g=JSON.parse(localStorage.getItem(key)||'null');return g&&Array.isArray(g.samples)&&g.samples.length>4?g:null;}catch{return null;}};
const fmt=ms=>{ms=Math.max(0,Number(ms)||0);const m=Math.floor(ms/60000),s=(ms%60000)/1000;return`${m}:${s.toFixed(3).padStart(6,'0')}`;};
function replayGeometry(samples){const xs=samples.map(s=>Number(s.x)).filter(Number.isFinite),ys=samples.map(s=>Number(s.y)).filter(Number.isFinite);if(!xs.length||!ys.length)return null;const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),spanX=Math.max(1,maxX-minX),spanY=Math.max(1,maxY-minY),pad=34,w=760,h=330,scale=Math.min((w-pad*2)/spanX,(h-pad*2)/spanY),ox=(w-spanX*scale)/2,oy=(h-spanY*scale)/2;const pts=samples.map(s=>({x:ox+(Number(s.x)-minX)*scale,y:oy+(Number(s.y)-minY)*scale,t:Number(s.t)||0,r:Number(s.r)||0}));return{w,h,pts,path:pts.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' ')};}

export class StatsScene extends CompactStatsScene{
  _installBroadcastStyles(){super._installBroadcastStyles();if(this._root?.querySelector('[data-br-replay-style]'))return;const s=document.createElement('style');s.dataset.brReplayStyle='1';s.textContent=`
.br-lap{position:relative}.br-play{width:25px;height:25px;border:1px solid #55eaff;background:rgba(20,75,91,.38);color:#fff;font-size:10px;font-weight:1000;display:grid;place-items:center;cursor:pointer;box-shadow:0 0 12px rgba(77,235,255,.1)}.br-play:hover,.br-play:active{background:#17475a}.br-lap.has-replay{grid-template-columns:22px minmax(0,1fr) auto 25px}.br-monitor{min-height:356px;padding:0;background:radial-gradient(circle at 50% 42%,rgba(35,132,160,.18),transparent 42%),linear-gradient(145deg,#071b27,#020a10)}.br-monitor-head{height:48px;padding:9px 12px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(94,236,255,.18)}.br-monitor-head strong{display:block;font-size:13px}.br-monitor-head small{display:block;color:#76909f;font-size:7px;font-weight:900}.br-monitor-live{color:#ff6f7c;border:1px solid #9b3946;padding:5px 8px;font-size:7px;font-weight:1000;letter-spacing:.15em}.br-screen{position:relative;height:280px;overflow:hidden;background-image:linear-gradient(rgba(69,213,235,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(69,213,235,.035) 1px,transparent 1px);background-size:28px 28px}.br-screen svg{width:100%;height:100%;display:block}.br-track-line{fill:none;stroke:rgba(182,224,231,.24);stroke-width:12;stroke-linecap:round;stroke-linejoin:round}.br-track-core{fill:none;stroke:#4ee7f7;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;filter:drop-shadow(0 0 5px rgba(78,231,247,.5))}.br-replay-car{fill:#f5ca5c;stroke:#fff;stroke-width:2;filter:drop-shadow(0 0 7px rgba(245,202,92,.8))}.br-replay-hud{position:absolute;left:10px;right:10px;top:9px;display:flex;justify-content:space-between;pointer-events:none}.br-replay-hud div{background:rgba(2,10,16,.82);border:1px solid rgba(86,232,249,.25);padding:6px 8px}.br-replay-hud small{display:block;color:#6fefff;font-size:6px;font-weight:1000;letter-spacing:.14em}.br-replay-hud strong{font-size:15px;font-variant-numeric:tabular-nums}.br-controls{height:42px;display:grid;grid-template-columns:auto 1fr auto;gap:9px;align-items:center;padding:6px 10px;border-top:1px solid rgba(94,236,255,.15)}.br-controls button{height:28px;min-width:48px;border:1px solid #386b7c;background:#0a2531;color:#fff;font-weight:1000}.br-seek{height:5px;background:#18313c;position:relative}.br-seek>i{position:absolute;inset:0 auto 0 0;width:0;background:#55efff;box-shadow:0 0 9px rgba(85,239,255,.55)}.br-analysis-back{color:#77eefa!important}
`;this._root.appendChild(s);}
  _renderBroadcastRecords(trackId=null){this._stopRaceControlReplay();super._renderBroadcastRecords(trackId);this._decorateReplayEntries();}
  _decorateReplayEntries(){const rows=[...(this._root?.querySelectorAll('.br-lap')||[])],all=this._root?.querySelectorAll('[data-br-track]')||[];let selectedId='';for(const el of all)if(el.classList.contains('active'))selectedId=el.dataset.brTrack||'';const state=this._getSelectedRecord(selectedId);if(!state)return;const laps=Array.isArray(state.topLaps)?state.topLaps.slice(0,10):[];rows.forEach((row,index)=>{const lap=laps[index];if(!lap)return;let key=lap.replayKey||null;if(!key&&state.ghostKey&&Math.abs(Number(lap.lapMs)-Number(state.bestLapMs))<=1)key=state.ghostKey;if(!key)return;const ghost=readGhost(key);if(!ghost)return;row.classList.add('has-replay');const b=document.createElement('button');b.className='br-play';b.type='button';b.title='Ver repetición';b.textContent='▶';b.addEventListener('click',()=>this._showRaceControlReplay({...state,selectedLap:lap},ghost));row.appendChild(b);});}
  _getSelectedRecord(trackId){try{const raw=JSON.parse(localStorage.getItem('tdr2:raceRecords:v1')||'null');return raw?.tracks?.[trackId]||null;}catch{return null;}}
  _showRaceControlReplay(record,ghost){this._stopRaceControlReplay();const main=this._root?.querySelector('.br-main');if(!main)return;const geo=replayGeometry(ghost.samples);if(!geo)return;this._brAnalysisMarkup=main.innerHTML;main.innerHTML=`<section class="br-panel br-monitor"><div class="br-monitor-head"><div><div class="br-label">RACE CONTROL // REPLAY</div><strong>${String(record.trackId||'CIRCUITO').toUpperCase()}</strong><small>${String(ghost.carId||'COCHE').toUpperCase()} · VUELTA ${fmt(ghost.lapMs)}</small></div><span class="br-monitor-live">● REPLAY</span></div><div class="br-screen"><svg viewBox="0 0 ${geo.w} ${geo.h}" preserveAspectRatio="xMidYMid meet"><polyline class="br-track-line" points="${geo.path}"/><polyline class="br-track-core" points="${geo.path}"/><circle class="br-replay-car" cx="${geo.pts[0].x}" cy="${geo.pts[0].y}" r="8"/></svg><div class="br-replay-hud"><div><small>TIEMPO</small><strong data-br-replay-time>0:00.000</strong></div><div><small>VUELTA</small><strong>${fmt(ghost.lapMs)}</strong></div></div></div><div class="br-controls"><button data-br-toggle>Ⅱ</button><div class="br-seek"><i></i></div><button class="br-analysis-back" data-br-analysis>ANÁLISIS</button></div></section>`;const car=main.querySelector('.br-replay-car'),timeEl=main.querySelector('[data-br-replay-time]'),bar=main.querySelector('.br-seek i'),toggle=main.querySelector('[data-br-toggle]');let playing=true,start=performance.now(),elapsed=0;const duration=Number(ghost.lapMs)||geo.pts.at(-1)?.t||1;const pointAt=t=>{let i=1;while(i<geo.pts.length&&geo.pts[i].t<t)i++;const a=geo.pts[Math.max(0,i-1)],b=geo.pts[Math.min(geo.pts.length-1,i)];const span=Math.max(1,b.t-a.t),q=Math.max(0,Math.min(1,(t-a.t)/span));return{x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q};};const frame=now=>{if(!this._brReplayState)return;if(playing)elapsed=Math.min(duration,elapsed+(now-start));start=now;const p=pointAt(elapsed);car?.setAttribute('cx',p.x);car?.setAttribute('cy',p.y);if(timeEl)timeEl.textContent=fmt(elapsed);if(bar)bar.style.width=`${Math.min(100,elapsed/duration*100)}%`;if(elapsed>=duration){playing=false;if(toggle)toggle.textContent='↻';}this._brReplayState.raf=requestAnimationFrame(frame);};this._brReplayState={raf:requestAnimationFrame(frame)};toggle?.addEventListener('click',()=>{if(elapsed>=duration){elapsed=0;playing=true;toggle.textContent='Ⅱ';start=performance.now();return;}playing=!playing;toggle.textContent=playing?'Ⅱ':'▶';start=performance.now();});main.querySelector('[data-br-analysis]')?.addEventListener('click',()=>this._restoreRaceControlAnalysis(main));}
  _restoreRaceControlAnalysis(main){this._stopRaceControlReplay();if(this._brAnalysisMarkup){main.innerHTML=this._brAnalysisMarkup;this._brAnalysisMarkup=null;}}
  _stopRaceControlReplay(){if(this._brReplayState?.raf)cancelAnimationFrame(this._brReplayState.raf);this._brReplayState=null;}
}
