import Phaser from 'phaser';
import { BaseScene } from './BaseScene.js';
import { createTrack, getTrackKeys } from '../tracks/trackRegistry.js';

function pts(track){return (track?.centerline||[]).map(p=>Array.isArray(p)?{x:p[0],y:p[1]}:p).filter(p=>Number.isFinite(p?.x)&&Number.isFinite(p?.y));}
function lengthOf(track){const p=pts(track);let d=0;for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length];d+=Math.hypot(b.x-a.x,b.y-a.y);}return Math.round(d);}
function sectorsOf(track){const c=track?.checkpointFractions;return Array.isArray(c)?Math.max(1,c.length+1):3;}
function surfaceOf(track){const s=String(track?.meta?.trackSurface||track?.meta?.surface||track?.surface||'').toLowerCase();if(s.includes('dirt')||s.includes('gravel')||s.includes('tierra'))return'Tierra';if(s.includes('snow')||s.includes('ice'))return'Nieve';if(s.includes('sand'))return'Arena';return'Asfalto';}

export class TrackGarageScene extends BaseScene{
 constructor(){super({key:'TrackGarageScene'});this._tracks=[];this._index=0;this._page=0;this._ui=null;this._mode='player';this._downX=0;}
 init(data){this._mode=data?.mode==='admin'?'admin':'player';}
 create(){super.create();this.cameras.main.setBackgroundColor('#05080b');this._tracks=getTrackKeys().map(k=>createTrack(k));let saved=null;try{saved=localStorage.getItem('tdr2:trackKey');}catch{}const i=this._tracks.findIndex(t=>t.key===saved);this._index=i>=0?i:0;this._page=Math.floor(this._index/8);this.scale.on('resize',this._render,this);this.input.on('wheel',(_p,_g,dx,dy)=>{if(Math.abs(dy)>5)this._changePage(dy>0?1:-1);});this.input.on('pointerdown',p=>this._downX=p.x);this.input.on('pointerup',p=>{const dx=p.x-this._downX;if(Math.abs(dx)>100)this._changePage(dx<0?1:-1);});this._render();}
 shutdown(){this.scale.off('resize',this._render,this);}
 _changePage(dir){const pages=Math.max(1,Math.ceil(this._tracks.length/8));this._page=(this._page+dir+pages)%pages;const first=this._page*8;if(this._index<first||this._index>=first+8)this._index=first;this._render();}
 _preview(track,w=720,h=470){const key=`grid_track_${track.key}_${w}_${h}`;if(this.textures.exists(key))return key;const g=this.make.graphics({add:false});g.fillStyle(0x716b58,1);g.fillRect(0,0,w,h);const p=pts(track);if(p.length>1){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;p.forEach(q=>{minX=Math.min(minX,q.x);minY=Math.min(minY,q.y);maxX=Math.max(maxX,q.x);maxY=Math.max(maxY,q.y);});const bw=Math.max(1,maxX-minX),bh=Math.max(1,maxY-minY),pad=45,s=Math.min((w-pad*2)/bw,(h-pad*2)/bh),ox=(w-bw*s)/2,oy=(h-bh*s)/2,d=p.map(q=>({x:ox+(q.x-minX)*s,y:oy+(q.y-minY)*s}));const tw=Math.max(10,Number(track.trackWidth||100)*s),grass=Math.max(tw+24,tw+Number(track.grassMargin||120)*s*1.25);const stroke=(lw,col,a)=>{g.lineStyle(lw,col,a);g.beginPath();g.moveTo(d[0].x,d[0].y);for(let i=1;i<d.length;i++)g.lineTo(d[i].x,d[i].y);g.closePath();g.strokePath();};stroke(grass,0x254c2d,1);stroke(tw+4,0xd8d6cb,.9);stroke(tw,0x292727,1);}g.generateTexture(key,w,h);g.destroy();return key;}
 _text(add,x,y,text,size,color='#fff',originX=0,originY=0,italic=false){const o=this.add.text(x,y,text,{fontFamily:'Arial Narrow,Arial,system-ui,sans-serif',fontSize:`${size}px`,fontStyle:italic?'bold italic':'bold',color,stroke:'#000000',strokeThickness:size>=22?1:0}).setOrigin(originX,originY);o.setResolution(Math.min(3,Math.max(2,window.devicePixelRatio||2)));return add(o);}
 _render(){const {width,height}=this.scale;if(this._ui)this._ui.destroy(true);this._ui=this.add.container(0,0);const add=o=>{this._ui.add(o);return o;};const sx=width/1536,sy=height/864,s=Math.min(sx,sy),X=v=>v*sx,Y=v=>v*sy,S=v=>Math.max(9,Math.round(v*s));
 const bg=add(this.add.graphics());bg.fillGradientStyle(0x05080b,0x0b1014,0x05070a,0x0b0e11,1);bg.fillRect(0,0,width,height);bg.lineStyle(1,0xffffff,.025);for(let x=-height;x<width;x+=X(46))bg.lineBetween(x,0,x+height,height);
 this._text(add,X(30),Y(20),'🏁',S(35),'#f7c500');this._text(add,X(82),Y(21),'SELECCIÓN DE ',S(34),'#ffffff',0,0,true);this._text(add,X(365),Y(21),'CIRCUITO',S(34),'#f7c500',0,0,true);const line=add(this.add.rectangle(0,Y(76),width,Y(2),0xf1bd00,1).setOrigin(0));
 const pages=Math.max(1,Math.ceil(this._tracks.length/8)),start=this._page*8,items=this._tracks.slice(start,start+8);const marginX=X(28),top=Y(98),gapX=X(18),gapY=Y(18),bottomSpace=Y(72),cardW=(width-marginX*2-gapX*3)/4,cardH=(height-top-bottomSpace-gapY)/2;
 items.forEach((t,j)=>{const idx=start+j,row=Math.floor(j/4),col=j%4,x=marginX+col*(cardW+gapX),y=top+row*(cardH+gapY),selected=idx===this._index;const card=add(this.add.rectangle(x,y,cardW,cardH,0x0b0f12,.98).setOrigin(0).setStrokeStyle(selected?3:2,selected?0xf5c400:0x3d4245,selected?1:.9).setInteractive({useHandCursor:true}));card.on('pointerdown',()=>{this._index=idx;this._render();});
  const headH=Y(44);add(this.add.rectangle(x,y,cardW,headH,selected?0x181b1d:0x111416,1).setOrigin(0));add(this.add.polygon(x+X(25),y+headH/2,[0,-headH/2,X(52),-headH/2,X(42),headH/2,-X(10),headH/2],0xf5c400,1));this._text(add,x+X(13),y+Y(9),String(idx+1).padStart(2,'0'),S(20),'#111111',0,0,true);this._text(add,x+X(66),y+Y(10),String(t.name||'CIRCUITO').toUpperCase(),S(19),'#ffffff',0,0,true);
  const statsH=Y(68),imgY=y+headH,imgH=cardH-headH-statsH;add(this.add.rectangle(x,imgY,cardW,imgH,0x5f5a4c,1).setOrigin(0));const img=add(this.add.image(x+cardW/2,imgY+imgH/2,this._preview(t)));img.setScale(Math.min(cardW/img.width,imgH/img.height));
  add(this.add.rectangle(x,y+cardH-statsH,cardW,statsH,0x090c0e,1).setOrigin(0));const stats=[['LONGITUD',`${lengthOf(t)} u`],['SECTORES',String(sectorsOf(t))],['SUPERFICIE',surfaceOf(t)],['ANCHO PISTA',`${Math.round(t.trackWidth||0)} u`]];stats.forEach((st,k)=>{const cw=cardW/4,cx=x+k*cw;if(k)add(this.add.rectangle(cx,y+cardH-statsH+Y(8),1,statsH-Y(16),0x64696c,.45).setOrigin(.5,0));this._text(add,cx+cw/2,y+cardH-statsH+Y(14),st[0],S(9),'#d5d8da',.5,0);this._text(add,cx+cw/2,y+cardH-statsH+Y(39),st[1],S(14),'#ffffff',.5,0);});
 });
 const by=height-Y(54);const back=add(this.add.rectangle(X(28),by,X(180),Y(40),0x12171b,1).setOrigin(0).setStrokeStyle(1,0x5b6266,.7).setInteractive({useHandCursor:true}));this._text(add,X(47),by+Y(9),'←  VOLVER',S(15),'#ffffff');back.on('pointerdown',()=>this.scene.start(this._mode==='admin'?'admin-hub':'menu'));
 const track=this._tracks[this._index];const bw=X(245),select=add(this.add.rectangle(width-X(28)-bw,by,bw,Y(40),0xf5bd00,1).setOrigin(0).setStrokeStyle(1,0xffdd55,1).setInteractive({useHandCursor:true}));this._text(add,width-X(28)-bw/2,by+Y(10),this._mode==='admin'?'🏁  EDITAR':'🏁  SELECCIONAR',S(15),'#15191b',.5,0);select.on('pointerdown',()=>{try{localStorage.setItem('tdr2:trackKey',track.key);}catch{}if(this._mode==='admin')this.scene.start('track-editor',{trackKey:track.key});else this.scene.start('menu');});
 if(pages>1){this._text(add,width/2,by+Y(11),`‹   ${this._page+1} / ${pages}   ›`,S(14),'#c7cdd0',.5,0);const prev=add(this.add.rectangle(width/2-X(75),by,X(45),Y(36),0x000000,0.01).setOrigin(.5,0).setInteractive());prev.on('pointerdown',()=>this._changePage(-1));const next=add(this.add.rectangle(width/2+X(75),by,X(45),Y(36),0x000000,0.01).setOrigin(.5,0).setInteractive());next.on('pointerdown',()=>this._changePage(1));}
 }
}
