import Phaser from 'phaser';
import { GARAGE_ITEMS, findRecipe } from '../garage/partsCatalog.js';
import { loadGarage, qty, craft, equip, getEquippedForCar } from '../garage/garageStore.js';

const FAMILIES=['engine','brakes','tires','suspension','transmission'];
const LABEL={engine:'MOTOR',brakes:'FRENOS',tires:'RUEDAS',suspension:'SUSPENSIÓN',transmission:'CAJA'};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const inside=(p,r)=>r&&p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h;
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);

function carId(){try{return localStorage.getItem('tdr2:carId')||'stock';}catch{return 'stock';}}

export class UpgradeShopScene extends Phaser.Scene{
  constructor(){super('upgrade-shop');this.state=null;this.filter='materials';this.tokens=[];this.views=new Map();this.drag=null;this.uid=1;this.board=null;this.mount={};this.ui=null;this.hoverUid=null;}
  create(){this.car=carId();this.state=loadGarage();this.input.on('pointermove',this._move,this);this.input.on('pointerup',this._up,this);this.scale.on('resize',this.render,this);this.events.once('shutdown',()=>{this.input.off('pointermove',this._move,this);this.input.off('pointerup',this._up,this);this.scale.off('resize',this.render,this);});this.render();}
  render(){
    const {width:w,height:h}=this.scale;if(this.ui)this.ui.destroy(true);this.ui=this.add.container();this.views.clear();this.mount={};const A=o=>{this.ui.add(o);return o;};
    const bg=A(this.add.graphics());bg.fillGradientStyle(0x061015,0x0b171b,0x071116,0x10231c,1).fillRect(0,0,w,h);bg.lineStyle(1,0xffffff,.025);for(let x=0;x<w;x+=90)bg.lineBetween(x,0,x,h);for(let y=0;y<h;y+=90)bg.lineBetween(0,y,w,y);
    const pad=18,head=70,left=Math.max(270,w*.22),right=Math.max(270,w*.22),gap=12,bx=pad+left+gap,bw=w-pad-right-gap-bx,top=head,ch=h-head-pad;
    A(this.add.text(pad,13,'TDR WORKSHOP',{fontFamily:'Orbitron,system-ui',fontSize:'28px',fontStyle:'900',color:'#f4fbff'}));A(this.add.text(pad,46,'COGE  →  ACERCA  →  FUSIONA  →  MONTA',{fontFamily:'system-ui',fontSize:'10px',fontStyle:'900',color:'#60efa8'}));
    A(this.add.text(w-pad,22,'← GARAGE',{fontFamily:'system-ui',fontSize:'12px',fontStyle:'900',color:'#fff'}).setOrigin(1,0).setInteractive()).on('pointerdown',()=>this.scene.start('menu'));
    this._panel(A,pad,top,left,ch,'MOCHILA',0x56eaa2);this._panel(A,bx,top,bw,ch,'BANCO DE TRABAJO',0x55c9ff);this._panel(A,w-pad-right,top,right,ch,'MONTAJE',0xffca58);
    this._inventory(A,{x:pad,y:top,w:left,h:ch});this._board(A,{x:bx,y:top,w:bw,h:ch});this._car(A,{x:w-pad-right,y:top,w:right,h:ch});this._tokens(A);
  }
  _panel(A,x,y,w,h,title,col){const g=A(this.add.graphics());g.fillStyle(0x081419,.96).fillRoundedRect(x,y,w,h,16);g.lineStyle(1,col,.45).strokeRoundedRect(x,y,w,h,16);g.fillStyle(col,.1).fillRoundedRect(x+1,y+1,w-2,42,15);A(this.add.text(x+16,y+13,title,{fontFamily:'Orbitron,system-ui',fontSize:'11px',fontStyle:'900',color:'#fff'}));}
  _inventory(A,r){
    const tw=(r.w-42)/2,y=r.y+52;this._tab(A,r.x+14,y,tw,'MATERIALES','materials');this._tab(A,r.x+28+tw,y,tw,'PIEZAS','parts');
    const ids=Object.keys(GARAGE_ITEMS).filter(id=>qty(this.state,id)>0).filter(id=>this.filter==='parts'?GARAGE_ITEMS[id].kind==='part':GARAGE_ITEMS[id].kind!=='part');const cols=2,g=9,cw=(r.w-37)/2,hh=88,sy=y+42;
    ids.slice(0,10).forEach((id,i)=>{const x=r.x+14+(i%cols)*(cw+g),yy=sy+Math.floor(i/2)*(hh+g);if(yy+hh>r.y+r.h-10)return;this._card(A,id,x,yy,cw,hh);});
  }
  _tab(A,x,y,w,label,key){const on=this.filter===key;const q=A(this.add.rectangle(x,y,w,30,on?0x1d4d39:0x102027).setOrigin(0).setStrokeStyle(1,on?0x59eda5:0x30464f).setInteractive());A(this.add.text(x+w/2,y+15,label,{fontFamily:'system-ui',fontSize:'8px',fontStyle:'900',color:on?'#d7ffe8':'#70868e'}).setOrigin(.5));q.on('pointerdown',()=>{if(!this.drag){this.filter=key;this.render();}});}
  _card(A,id,x,y,w,h){const item=GARAGE_ITEMS[id],c=A(this.add.container(x,y)),g=this.add.graphics();c.add(g);g.fillStyle(0x0c1b21).fillRoundedRect(0,0,w,h,11);g.lineStyle(1,item.tone||0x5ecfff,.5).strokeRoundedRect(0,0,w,h,11);g.fillStyle(item.tone||0x5ecfff,.13).fillRoundedRect(5,5,w-10,49,8);this._art(c,item,w/2,29,48);c.add(this.add.text(w-8,7,`×${qty(this.state,id)}`,{fontFamily:'Orbitron,system-ui',fontSize:'9px',fontStyle:'900',color:'#75eaff'}).setOrigin(1,0));c.add(this.add.text(w/2,65,item.name,{fontFamily:'system-ui',fontSize:'8px',fontStyle:'900',color:'#fff',align:'center',wordWrap:{width:w-12}}).setOrigin(.5,0));c.setSize(w,h).setInteractive(new Phaser.Geom.Rectangle(0,0,w,h),Phaser.Geom.Rectangle.Contains);c.on('pointerdown',p=>this._startInventory(id,p));}
  _board(A,r){this.board={x:r.x+12,y:r.y+50,w:r.w-24,h:r.h-62};const b=this.board,g=A(this.add.graphics());g.fillStyle(0x07131a).fillRoundedRect(b.x,b.y,b.w,b.h,20);g.lineStyle(2,0x55c9ff,.25).strokeRoundedRect(b.x,b.y,b.w,b.h,20);g.lineStyle(1,0x5acbff,.06);for(let x=b.x+50;x<b.x+b.w;x+=70)g.lineBetween(x,b.y+10,x,b.y+b.h-10);for(let y=b.y+70;y<b.y+b.h;y+=70)g.lineBetween(b.x+10,y,b.x+b.w-10,y);A(this.add.text(b.x+b.w/2,b.y+22,'MESA LIBRE · COLOCA DONDE QUIERAS',{fontFamily:'Orbitron,system-ui',fontSize:'9px',fontStyle:'900',color:'#8bdcff'}).setOrigin(.5));A(this.add.text(b.x+b.w/2,b.y+42,'Acerca dos objetos compatibles: se iluminarán antes de fusionar.',{fontFamily:'system-ui',fontSize:'8px',fontStyle:'700',color:'#69828d'}).setOrigin(.5));}
  _tokens(A){for(const t of this.tokens){const item=GARAGE_ITEMS[t.id];if(!item)continue;const c=A(this.add.container(t.x,t.y).setDepth(100)),g=this.add.graphics();c.add(g);const hi=this.hoverUid===t.uid;g.fillStyle(hi?0x143d31:0x09171d,.98).fillCircle(0,0,hi?49:46);g.lineStyle(hi?5:3,hi?0x66ffae:(item.tone||0x62d8ff),hi?1:.8).strokeCircle(0,0,hi?49:46);this._art(c,item,0,-4,62);c.add(this.add.text(0,37,item.name,{fontFamily:'system-ui',fontSize:'7px',fontStyle:'900',color:'#fff',backgroundColor:'#071116',padding:{x:5,y:2}}).setOrigin(.5));c.setSize(100,100).setInteractive(new Phaser.Geom.Circle(50,50,50),Phaser.Geom.Circle.Contains);c.on('pointerdown',p=>this._startToken(t.uid,p));this.views.set(t.uid,c);}}
  _car(A,r){A(this.add.text(r.x+16,r.y+55,'ARRASTRA AQUÍ LAS PIEZAS',{fontFamily:'system-ui',fontSize:'8px',fontStyle:'900',color:'#83979e'}));const eq=getEquippedForCar(this.state,this.car),x=r.x+14,w=r.w-28,hh=58,sy=r.y+88;FAMILIES.forEach((f,i)=>{const y=sy+i*(hh+8),id=eq?.[f],item=id?GARAGE_ITEMS[id]:null,g=A(this.add.graphics());g.fillStyle(item?0x17392b:0x0d1b20).fillRoundedRect(x,y,w,hh,10);g.lineStyle(2,item?0x59eda5:0x334c55,.65).strokeRoundedRect(x,y,w,hh,10);A(this.add.text(x+12,y+8,LABEL[f],{fontFamily:'system-ui',fontSize:'8px',fontStyle:'900',color:'#82969d'}));if(item){this._art(A(this.add.container()),item,x+34,y+37,32);A(this.add.text(x+56,y+31,item.name,{fontFamily:'system-ui',fontSize:'9px',fontStyle:'900',color:'#fff'}));}else A(this.add.text(x+12,y+31,'SUELTA PIEZA',{fontFamily:'system-ui',fontSize:'9px',fontStyle:'900',color:'#4e6871'}));this.mount[f]={x,y,w,h:hh};});}
  _startInventory(id,p){if(this.drag||qty(this.state,id)<=this._reserved(id))return;const item=GARAGE_ITEMS[id];const v=this._ghost(item,p.x,p.y);this.drag={kind:'inventory',id,v,x:p.x,y:p.y};}
  _startToken(uid,p){if(this.drag)return;const t=this.tokens.find(q=>q.uid===uid),v=this.views.get(uid);if(!t||!v)return;v.setDepth(2000).setScale(1.12);this.drag={kind:'token',id:t.id,uid,v,ox:p.x-v.x,oy:p.y-v.y,x:p.x,y:p.y};}
  _ghost(item,x,y){const c=this.add.container(x,y).setDepth(3000),g=this.add.graphics();c.add(g);g.fillStyle(0x0a1b21,.96).fillCircle(0,0,48);g.lineStyle(4,item.tone||0x5ed4ff,.95).strokeCircle(0,0,48);this._art(c,item,0,0,66);return c;}
  _move(p){if(!this.drag)return;const d=this.drag;d.x=p.x;d.y=p.y;if(d.kind==='token'){d.v.x=p.x-d.ox;d.v.y=p.y-d.oy;}else{d.v.x=p.x;d.v.y=p.y;}const pos={x:d.kind==='token'?d.v.x:p.x,y:d.kind==='token'?d.v.y:p.y};const candidate=this.tokens.filter(t=>t.uid!==d.uid&&findRecipe(d.id,t.id)).sort((a,b)=>distance(pos,a)-distance(pos,b))[0];const next=candidate&&distance(pos,candidate)<125?candidate.uid:null;if(next!==this.hoverUid){this.hoverUid=next;for(const [uid,v] of this.views){if(uid===d.uid)continue;v.setScale(uid===next?1.16:1);}if(next){const v=this.views.get(next);if(v)this.tweens.add({targets:v,scaleX:1.22,scaleY:1.22,duration:90,yoyo:true});}}}
  _up(p){if(!this.drag)return;const d=this.drag;this.drag=null;const target=this.hoverUid;this.hoverUid=null;if(d.kind==='inventory'){d.v.destroy(true);this._dropInventory(d,p,target);}else this._dropToken(d,p,target);}
  _dropInventory(d,p,target){const item=GARAGE_ITEMS[d.id];if(item?.kind==='part'&&inside(p,this.mount[item.family])&&equip(this.state,d.id,this.car)){this.state=loadGarage();this._toast(`${item.name} montada`);this.render();return;}if(!inside(p,this.board))return;if(qty(this.state,d.id)<=this._reserved(d.id))return this._toast('No quedan unidades libres');const t={uid:this.uid++,id:d.id,x:clamp(p.x,this.board.x+55,this.board.x+this.board.w-55),y:clamp(p.y,this.board.y+72,this.board.y+this.board.h-55)};this.tokens.push(t);if(target)this._tryFusion(t.uid,target);else this.render();}
  _dropToken(d,p,target){const t=this.tokens.find(q=>q.uid===d.uid);if(!t)return this.render();const item=GARAGE_ITEMS[t.id];if(item?.kind==='part'&&inside(p,this.mount[item.family])&&equip(this.state,t.id,this.car)){this.state=loadGarage();this.tokens=this.tokens.filter(q=>q.uid!==t.uid);this._toast(`${item.name} montada`);this.render();return;}if(!inside(p,this.board)){this.tokens=this.tokens.filter(q=>q.uid!==t.uid);this.render();return;}t.x=clamp(d.v.x,this.board.x+55,this.board.x+this.board.w-55);t.y=clamp(d.v.y,this.board.y+72,this.board.y+this.board.h-55);d.v.setScale(1);if(target)this._tryFusion(t.uid,target);else this.render();}
  _tryFusion(aUid,bUid){const a=this.tokens.find(t=>t.uid===aUid),b=this.tokens.find(t=>t.uid===bUid);if(!a||!b||!findRecipe(a.id,b.id))return this.render();const x=b.x,y=b.y;const res=craft(this.state,a.id,b.id);if(!res.ok){this._toast(res.reason||'No se puede fusionar');return this.render();}this.state=loadGarage();this.tokens=this.tokens.filter(t=>t.uid!==aUid&&t.uid!==bUid);this._fusionAnim(a,b,x,y,res.item);}
  _fusionAnim(a,b,x,y,item){const va=this.views.get(a.uid),vb=this.views.get(b.uid);if(va&&vb){va.setDepth(3500);vb.setDepth(3500);this.tweens.add({targets:[va,vb],x,y,scaleX:.35,scaleY:.35,angle:'+=18',duration:150,ease:'Quad.easeIn',onComplete:()=>this._finishFusion(x,y,item)});}else this._finishFusion(x,y,item);}
  _finishFusion(x,y,item){const ring=this.add.graphics().setDepth(4000);ring.lineStyle(6,item.tone||0x62efa8,1).strokeCircle(x,y,24);this.tweens.add({targets:ring,alpha:0,scaleX:3,scaleY:3,duration:360,onComplete:()=>ring.destroy()});this.cameras.main.shake(90,.0015);this.tokens.push({uid:this.uid++,id:item.id,x,y});this._toast(`¡${item.name.toUpperCase()} CREADA!`);this.render();}
  _reserved(id){return this.tokens.filter(t=>t.id===id).length;}
  _toast(msg){const {width,height}=this.scale,t=this.add.text(width/2,height-28,msg,{fontFamily:'Orbitron,system-ui',fontSize:'11px',fontStyle:'900',color:'#fff',backgroundColor:'#154332',padding:{x:16,y:9}}).setOrigin(.5).setDepth(6000);this.tweens.add({targets:t,alpha:0,y:t.y-10,delay:850,duration:300,onComplete:()=>t.destroy()});}
  _art(c,item,x,y,size){const g=this.add.graphics();c.add(g);g.x=x;g.y=y;const s=size/64,t=item.tone||0x74d7ff,id=item.id||'',fam=item.family;g.fillStyle(0x000000,.24).fillEllipse(2*s,18*s,48*s,12*s);if(id==='rubber'||fam==='tires'){g.fillStyle(0x101417).fillCircle(0,0,25*s);g.fillStyle(0x465159).fillCircle(0,0,16*s);g.fillStyle(0xbcc7cd).fillCircle(0,0,8*s);}else if(id==='spring'||fam==='suspension'){g.lineStyle(5*s,t,1);g.beginPath();g.moveTo(-20*s,-18*s);for(let i=0;i<9;i++)g.lineTo((i%2?19:-19)*s,(-18+i*5)*s);g.strokePath();}else if(id==='disc'||fam==='brakes'){g.fillStyle(0xc1ccd2).fillCircle(0,0,24*s);g.fillStyle(0x56636b).fillCircle(0,0,15*s);g.fillStyle(0x171d20).fillCircle(0,0,5*s);if(fam==='brakes')g.fillStyle(t).fillRoundedRect(8*s,-15*s,17*s,30*s,5*s);}else if(id==='gear'||fam==='transmission'){g.fillStyle(0xc5ae68).fillCircle(0,0,23*s);g.fillStyle(0x4f5148).fillCircle(0,0,10*s);for(let i=0;i<10;i++){const a=i*Math.PI/5;g.fillStyle(0xc5ae68).fillRect((Math.cos(a)*25-3)*s,(Math.sin(a)*25-3)*s,6*s,6*s);}}else if(id==='alloy'){g.fillStyle(0xa9bdc8);g.fillTriangle(-25*s,13*s,-13*s,-18*s,24*s,-7*s);g.fillStyle(0xe8f8ff,.5).fillTriangle(-13*s,-14*s,17*s,-6*s,-5*s,3*s);}else if(id==='scrap'){g.fillStyle(0x829199).fillRoundedRect(-24*s,-8*s,25*s,10*s,3*s);g.fillStyle(0xbac4c9).fillRoundedRect(-13*s,-18*s,9*s,29*s,3*s);g.fillStyle(0x697880).fillRoundedRect(4*s,-12*s,23*s,9*s,3*s);g.fillStyle(0x9ca9b0).fillCircle(16*s,9*s,7*s);}else if(id==='compound'){g.fillStyle(0xe39a36).fillRoundedRect(-23*s,-16*s,46*s,32*s,8*s);g.fillStyle(0xffc25e).fillRoundedRect(-17*s,-10*s,34*s,20*s,6*s);}else if(id==='ecu'){g.fillStyle(0x1b5d49).fillRoundedRect(-25*s,-17*s,50*s,34*s,5*s);g.fillStyle(0x63e5b1);for(let i=-14;i<15;i+=7)g.fillRect(i*s,-6*s,4*s,4*s);}else if(fam==='engine'||id==='engine_block'){g.fillStyle(0x7d909b).fillRoundedRect(-27*s,-19*s,54*s,38*s,7*s);g.fillStyle(0xa9b7bf).fillRoundedRect(-19*s,-11*s,38*s,22*s,5*s);g.fillStyle(t).fillRect(-23*s,13*s,46*s,7*s);}else{g.fillStyle(t).fillCircle(0,0,21*s);g.fillStyle(0xffffff,.35).fillCircle(-7*s,-7*s,7*s);}}
}
