const KEY='tdr2:shipatonJudgeMode:v1';
const EVENT='tdr2:shipaton-judge-mode';
export function shipatonJudgeModeEnabled(){try{return localStorage.getItem(KEY)==='1';}catch{return false;}}
export function setShipatonJudgeMode(enabled){const value=!!enabled;try{localStorage.setItem(KEY,value?'1':'0');}catch{}try{window.dispatchEvent(new CustomEvent(EVENT,{detail:{enabled:value}}));}catch{}syncJudgeBadge();return value;}
export function toggleShipatonJudgeMode(){return setShipatonJudgeMode(!shipatonJudgeModeEnabled());}
// Read-only access authority: consumers may bypass access checks, never persist rewards/unlocks merely because it is active.
export function evaluationAccessEnabled(){return shipatonJudgeModeEnabled();}
export function syncJudgeBadge(){const active=shipatonJudgeModeEnabled();let badge=document.getElementById('tdr-shipaton-judge-badge');if(!active){badge?.remove();return}if(!badge){badge=document.createElement('div');badge.id='tdr-shipaton-judge-badge';badge.textContent='SHIP-A-TON ’26 · MODO JUECES';Object.assign(badge.style,{position:'fixed',right:'max(10px,env(safe-area-inset-right,0px))',bottom:'max(8px,env(safe-area-inset-bottom,0px))',zIndex:'8500',pointerEvents:'none',padding:'6px 9px',border:'1px solid rgba(255,102,37,.62)',borderRadius:'8px',background:'rgba(42,33,77,.88)',color:'#fff6e8',font:'800 9px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace',letterSpacing:'.08em'});document.body.appendChild(badge)}}
function openJudgePanel(){document.querySelector('.tdr-judge-modal')?.remove();const active=shipatonJudgeModeEnabled(),m=document.createElement('div');m.className='tdr-judge-modal';Object.assign(m.style,{position:'fixed',inset:'0',zIndex:'31000',background:'#000c',display:'grid',placeItems:'center',padding:'5vh 6vw',fontFamily:'system-ui',color:'#c9d4dd'});m.innerHTML=`<article style="width:min(760px,90vw);max-height:82vh;overflow:auto;background:#0b141d;border:1px solid #58e8ff88;border-radius:12px;padding:22px;box-shadow:0 20px 70px #000"><h2 style="margin:0;color:#fff">SHIPATON 2026 · MODO JUECES</h2><p>Acceso de evaluación para ver y probar el contenido sin convertir ese acceso en progresión normal.</p><div style="margin:14px 0;padding:11px;border:1px solid ${active?'#58e8ff':'#3b4b58'};border-radius:8px;color:${active?'#8eefff':'#c9d4dd'}">${active?'● MODO JUECES ACTIVO':'○ MODO JUECES DESACTIVADO'}</div><p><b style="color:#fff">GUÍA DEL JURADO</b><br>• Garaje: inspecciona y prueba la flota completa disponible.<br>• Circuitos: accede al contenido disponible para evaluación.<br>• Monetización: prueba Recicladora, vídeo recompensado de Tienda y x2 de botín postcarrera.<br>• Activar este modo no concede por sí mismo monedas, materiales ni desbloqueos permanentes.</p><div style="display:flex;gap:10px;margin-top:16px"><button data-close style="flex:1;padding:11px">CERRAR</button><button data-toggle style="flex:1;padding:11px;border:1px solid #58e8ff;background:#103c4a;color:#9bf2ff;font-weight:900">${active?'DESACTIVAR':'ACTIVAR'} MODO JUECES</button></div></article>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('[data-toggle]').onclick=()=>{setShipatonJudgeMode(!active);m.remove();openJudgePanel()}}
function styleShipatonTab(b){if(!b)return;b.setAttribute('aria-label','Ship-a-ton 2026 · Modo jueces');b.innerHTML='<span class="shipaton-mark" aria-hidden="true">✦</span><span class="shipaton-word">Ship-a-ton</span><span class="shipaton-year">26</span>';Object.assign(b.style,{position:'relative',overflow:'hidden',display:'flex',alignItems:'center',justifyContent:'center',gap:'clamp(3px,.45vw,7px)',background:'linear-gradient(180deg,#332958 0%,#251f43 100%)',border:'1px solid rgba(255,102,37,.72)',boxShadow:'inset 0 0 0 1px rgba(255,255,255,.035),0 0 14px rgba(255,102,37,.08)',color:'#fff7e9',fontFamily:'ui-monospace,SFMono-Regular,Menlo,Consolas,monospace',fontWeight:'800',letterSpacing:'0',textTransform:'none'});const mark=b.querySelector('.shipaton-mark'),word=b.querySelector('.shipaton-word'),year=b.querySelector('.shipaton-year');Object.assign(mark.style,{color:'#ff6625',fontSize:'1.05em',lineHeight:'1'});Object.assign(word.style,{whiteSpace:'nowrap',fontSize:'clamp(7px,.9vw,11px)'});Object.assign(year.style,{display:'inline-grid',placeItems:'center',minWidth:'22px',height:'18px',padding:'0 3px',border:'1px solid #ff6625',borderRadius:'2px',color:'#ff6625',fontSize:'clamp(7px,.82vw,10px)',lineHeight:'1',boxShadow:'inset 0 0 0 1px rgba(255,102,37,.15)'});}
function wireSettings(){const tabs=document.querySelector('#tdr-settings2 .s2tabs');if(!tabs)return;let b=tabs.querySelector('[data-shipaton-judge]');if(!b){b=document.createElement('button');b.className='s2tab';b.dataset.shipatonJudge='1';b.onclick=e=>{e.preventDefault();openJudgePanel()};tabs.appendChild(b)}styleShipatonTab(b)}
export const SHIPATON_JUDGE_MODE_KEY=KEY;export const SHIPATON_JUDGE_MODE_EVENT=EVENT;
if(typeof window!=='undefined'){queueMicrotask(()=>{syncJudgeBadge();wireSettings()});window.addEventListener('pageshow',()=>{syncJudgeBadge();wireSettings()},{passive:true});new MutationObserver(wireSettings).observe(document.documentElement,{subtree:true,childList:true});}
