import { GARAGE_ITEMS, DIRECT_CRAFT_RECIPES } from '../garage/partsCatalog.js';
import { loadGarage, saveGarage, qty, consume, addItem } from '../garage/garageStore.js';
export const PART_DISMANTLE_EFFICIENCY=0.90;
const MATERIALS=new Set(Object.values(GARAGE_ITEMS).filter(x=>x?.kind==='material').map(x=>x.id));
function flattenRecipe(partId,mult=1,out={}){const recipe=DIRECT_CRAFT_RECIPES[partId];if(!recipe?.requires)return out;for(const req of recipe.requires){const n=Math.max(0,Math.floor(Number(req.qty)||0))*mult;if(!n)continue;if(MATERIALS.has(req.id))out[req.id]=(out[req.id]||0)+n;else if(GARAGE_ITEMS[req.id]?.kind==='part')flattenRecipe(req.id,n,out);}return out;}
export function dismantleBaseMaterials(partId,count=1){return GARAGE_ITEMS[partId]?.kind==='part'?flattenRecipe(partId,Math.max(1,Math.floor(Number(count)||1)),{}):{};}
function equippedPartIds(s){const ids=new Set(Object.values(s?.equipped||{}));for(const car of Object.values(s?.equippedByCar||{}))for(const id of Object.values(car||{}))ids.add(id);return ids;}
export function dismantleAvailableCount(s,partId){return Math.max(0,Math.max(0,qty(s,partId))-(equippedPartIds(s).has(partId)?1:0));}
export function quotePartDismantle(partId,count=1,s=loadGarage()){const item=GARAGE_ITEMS[partId],n=Math.max(1,Math.floor(Number(count)||1));if(item?.kind!=='part')return{ok:false,reason:'Pieza no válida',returns:{}};const available=dismantleAvailableCount(s,partId);if(available<n)return{ok:false,reason:available>0?'Cantidad no disponible':'Pieza equipada: conserva al menos una unidad',returns:{},available};const base=dismantleBaseMaterials(partId,n),entries=Object.entries(base).filter(([,v])=>v>0),total=entries.reduce((a,[,v])=>a+v,0);if(!total)return{ok:false,reason:'Esta pieza no tiene receta recuperable',returns:{},available};const target=Math.max(0,Math.floor(total*PART_DISMANTLE_EFFICIENCY));const rows=entries.map(([id,v])=>({id,base:v,raw:v*PART_DISMANTLE_EFFICIENCY,n:Math.floor(v*PART_DISMANTLE_EFFICIENCY)}));let assigned=rows.reduce((a,r)=>a+r.n,0);rows.sort((a,b)=>(b.raw-b.n)-(a.raw-a.n)||b.base-a.base||a.id.localeCompare(b.id));for(let i=0;assigned<target&&i<rows.length;i++,assigned++)if(rows[i].n<rows[i].base)rows[i].n++;const returns={};for(const r of rows)if(r.n>0)returns[r.id]=r.n;return{ok:true,partId,count:n,available,base,returns,totalInput:total,totalReturn:Object.values(returns).reduce((a,v)=>a+v,0),fee:1-PART_DISMANTLE_EFFICIENCY};}
export function executePartDismantle(partId,count=1){const s=loadGarage(),q=quotePartDismantle(partId,count,s);if(!q.ok)return q;if(!consume(s,partId,q.count))return{ok:false,reason:'Inventario insuficiente'};for(const[id,n]of Object.entries(q.returns))addItem(s,id,n);saveGarage(s);return q;}
export function dismantleCandidates(s=loadGarage()){return Object.values(GARAGE_ITEMS).filter(x=>x?.kind==='part'&&qty(s,x.id)>0).map(item=>({item,owned:qty(s,item.id),available:dismantleAvailableCount(s,item.id)}));}

// DEV 1.1.101: part dismantling uses canonical recursive recipes, batch rounding, and protects equipped stock.
