// TrackStudio image-native projects: binary image in IndexedDB, portable .tdrtrack bundle.
const DB='tdr-trackstudio-image-v1', STORE='images', MAGIC='TDR-IMAGE-PROJECT-V1\n';
const enc=new TextEncoder(),dec=new TextDecoder();
function openDb(){return new Promise((ok,no)=>{if(typeof indexedDB==='undefined')return no(new Error('IndexedDB no disponible'));const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||new Error('Error abriendo IndexedDB'))})}
async function act(mode,id,value){const db=await openDb();return new Promise((ok,no)=>{const tx=db.transaction(STORE,mode),s=tx.objectStore(STORE),r=mode==='readonly'?s.get(id):s.put(value,id);let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>{db.close();ok(result)};tx.onerror=()=>{db.close();no(tx.error||new Error('Error almacenando imagen'))};tx.onabort=()=>{db.close();no(tx.error||new Error('Transacción cancelada'))}})}
export async function saveCanvasImage(id,blob,meta){if(!id||!(blob instanceof Blob)||!blob.size)throw Error('Imagen inválida');await act('readwrite',id,{blob,meta:{...meta,imageId:id}})}
export async function readCanvasImage(id){return id?act('readonly',id):null}
export function packImageProject(project,blob,meta){if(!(blob instanceof Blob)||!blob.size)throw Error('Falta la imagen maestra');const desc={...meta,size:blob.size,type:blob.type||meta?.type||'image/png'},json=enc.encode(JSON.stringify({...project,imageAsset:desc})),prefix=enc.encode(MAGIC+json.byteLength+'\n');return new Blob([prefix,json,blob],{type:'application/octet-stream'})}
export async function unpackImageProject(file){if(!(file instanceof Blob)||!file.size)throw Error('Archivo vacío');const lead=dec.decode(await file.slice(0,160).arrayBuffer());if(!lead.startsWith(MAGIC))throw Error('No es un proyecto TrackStudio Image');const match=lead.slice(MAGIC.length).match(/^(\d+)\n/);if(!match)throw Error('Cabecera incorrecta');const len=Number(match[1]),offset=enc.encode(MAGIC+match[1]+'\n').byteLength;if(!Number.isSafeInteger(len)||len<2||len>20_000_000||offset+len>=file.size)throw Error('Longitud incorrecta');const data=JSON.parse(dec.decode(await file.slice(offset,offset+len).arrayBuffer())),image=file.slice(offset+len,file.size,data.imageAsset?.type||'image/png');if(!data.editor?.imageCanvas||data.imageAsset?.size!==image.size)throw Error('Imagen ausente o incompleta');return{project:data,image}}
